chore(refactor): Move ComplianceOperator pipelines to compliance operator packages
stackrox/stackrox pull request #10488
Opened 2024-03-22 13:09 UTC by SimonBaeumer

## Description

Moved the pipeline packages belonging to the Compliance Operator integration to the complianceoperator packages. 
This is done because of several reasons:

 - The `pipeline` package is not scalable, it grows with every new added resource we synchronize in Central
 - Navigation and exploration of the source code is hard. One cannot find the logic which upserts new resources easily without knowing about the pipelines. 
 - Code belonging to a domain/use-case (e.g. complianceoperator) can be found in one location.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

 - CI

2024-03-22 13:17 UTC, dashrews78 commented on central/complianceoperator/pipelines/complianceoperator/complianceoperatorinfo/pipeline.go
This is actually a V2 pipeline which sort of illustrates why this change is a good idea.

So move this to v2 and I would also remove the second `complianceoperator` directory from this one.

2024-03-22 13:18 UTC, dashrews78 requested changes
Move the complianceoperatorinfo to v2.

2024-03-22 13:25 UTC, SimonBaeumer commented on central/complianceoperator/pipelines/complianceoperator/complianceoperatorinfo/pipeline.go
Great, already uncovered an issue. Fixed it.

2024-03-22 14:16 UTC, lvalerom reviewed
Looks good! Would it make sense to have the pipelines inside of each resource folder similarly to the `datastore` and `service` packages (e.g. `central/complianceopeartor/v2/rules/pipeline`). It would look something like this:

- central
    - complianceoperator
        - v2
            - rules
                - datastore
                - pipeline
                - store
            - profiles
                - datastore
                - pipeline
                - service
                - store

2024-03-25 16:09 UTC, SimonBaeumer commented
> Looks good! Would it make sense to have the pipelines inside of each resource folder similarly to the `datastore` and `service` packages (e.g. `central/complianceopeartor/v2/rules/pipeline`). It would look something like this:
> 
> * central
>   
>   * complianceoperator
>     
>     * v2
>       
>       * rules
>         
>         * datastore
>         * pipeline
>         * store
>       * profiles
>         
>         * datastore
>         * pipeline
>         * service
>         * store

Good observation. 
I've tried but did not liked the outcome. First not all resource could be mapped to one package, the `pipelines` directory would persist. 
It's to me a bit too make it worse and split the pipelines too much. With a bit more experience we can move them later into the respective packages.

2024-03-25 16:32 UTC, dashrews78 commented
> > Looks good! Would it make sense to have the pipelines inside of each resource folder similarly to the `datastore` and `service` packages (e.g. `central/complianceopeartor/v2/rules/pipeline`). It would look something like this:
> > 
> > * central
> >   
> >   * complianceoperator
> >     
> >     * v2
> >       
> >       * rules
> >         
> >         * datastore
> >         * pipeline
> >         * store
> >       * profiles
> >         
> >         * datastore
> >         * pipeline
> >         * service
> >         * store
> 
> Good observation. I've tried but did not liked the outcome. First not all resource could be mapped to one package, the `pipelines` directory would persist. It's to me a bit too make it worse and split the pipelines too much. With a bit more experience we can move them later into the respective packages.

I agree.  that's an interesting idea, but lets save that for a later and larger refactor

2024-03-25 16:59 UTC, dashrews78 approved these changes

2024-03-26 08:21 UTC, merged