chore(deps): bump cosign
stackrox/stackrox pull request #10731
Opened 2024-04-12 14:54 UTC by dhaus67

## Description

Bumping cosign dep to the latest released version.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

- see CI passing.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2024-04-12 15:44 UTC, janisz approved these changes

2024-04-16 09:37 UTC, janisz commented on go.mod
> +	google.golang.org/grpc v1.62.1
I think this breaks our test. How about adding a replace and pin it to 1.61.1?

2024-04-17 18:06 UTC, dcaravel requested changes
The version bump for `x/sync` broke a few of the delegated scanning unit tests, will need to update the tests.

Created a PR to demo a potential fix (based off this PR's branch): https://github.com/stackrox/stackrox/pull/10793

2024-04-18 16:51 UTC, dhaus67 commented
/retest

2024-04-18 18:41 UTC, dcaravel approved these changes
LGTM, thanks!

2024-04-18 19:34 UTC, dhaus67 commented
/retest

2024-04-18 20:28 UTC, merged