chore (proto): Add go package path to proto files to improve V2 migration
stackrox/stackrox pull request #10765
Opened 2024-04-16 15:25 UTC by mtodor

## Description

This PR is adding the path to proto files for the go package. This was done before 
with #10609, but it didn't work as expected. Providing a proper relative path should output files in the correct locations.

This PR changes:
- all proto files
- all generated `.pb.go` files (but only `fileDescriptor_`, not actual code)

**Note**

I made the following changes:
```
find ./proto/api/v1 -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/api\/v1;v1";/' {}
find ./proto/api/v2 -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/api\/v2;v2";/' {}
find ./proto/api/integrations -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/api\/integrations;integrations";/' {}
find ./proto/storage -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/storage;storage";/' {}
find ./proto/test -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/test;test";/' {}
find ./proto/tools/local-sensor -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/tools\/local-sensor;localSensor";/' {}
find ./proto/internalapi/central -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/internalapi\/central;central";/' {}
find ./proto/internalapi/compliance -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/internalapi\/compliance;compliance";/' {}
find ./proto/internalapi/sensor -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/internalapi\/central;sensor";/' {}
find ./proto/internalapi/wrapper -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/internalapi\/central;wrapper";/' {}
find ./proto/internalapi/scanner/v4 -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/internalapi\/scanner\/v4;v4";/' {}
```

And regenerated files with `make proto-generated-srcs`.

## Checklist
- [ ] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

Just CI run

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2024-04-16 17:46 UTC, dashrews78 commented on proto/internalapi/sensor/admission_control.proto
> +option go_package = "./internalapi/central;sensor";
```suggestion
option go_package = "./internalapi/sensor;sensor";
```

2024-04-16 17:47 UTC, dashrews78 commented on proto/internalapi/sensor/admission_control_iservice.proto
> +option go_package = "./internalapi/central;sensor";
`sensor`

2024-04-16 17:47 UTC, dashrews78 commented on proto/internalapi/sensor/cert_distribution_iservice.proto
> +option go_package = "./internalapi/central;sensor";
`sensor`

2024-04-16 17:48 UTC, dashrews78 requested changes
All the ones in `./internalapi/sensor` are incorrectly pathed to `./internalapi/central`

2024-04-16 17:57 UTC, janisz commented
is it working with v2?

2024-04-16 18:00 UTC, dashrews78 commented
> is it working with v2?

Seemed to be.  I pulled it down and made a couple of changes in `proto/api/v2/compliance_results_service.proto`.  Files were at least generated in the correct place.  But then I saw the errors below which make sense because all those protos are in `internalapi/sensor`:

```
Removing internalapi/central/deployment_iservice.pb.go because internalapi/central/deployment_iservice.proto does not exist
Removing internalapi/central/network_connection_iservice.pb.go because internalapi/central/network_connection_iservice.proto does not exist
Removing internalapi/central/image_iservice.pb.go because internalapi/central/image_iservice.proto does not exist
Removing internalapi/central/admission_control.pb.go because internalapi/central/admission_control.proto does not exist
Removing internalapi/central/compliance_iservice.pb.go because internalapi/central/compliance_iservice.proto does not exist
Removing internalapi/central/signal_iservice.pb.go because internalapi/central/signal_iservice.proto does not exist
Removing internalapi/central/admission_control_iservice.pb.go because internalapi/central/admission_control_iservice.proto does not exist
Removing internalapi/central/cert_distribution_iservice.pb.go because internalapi/central/cert_distribution_iservice.proto does not exist
Removing internalapi/central/network_connection_info.pb.go because internalapi/central/network_connection_info.proto does not exist
Removing internalapi/central/network_enums.pb.go because internalapi/central/network_enums.proto does not exist
Removing internalapi/central/splunk_alert.pb.go because internalapi/central/splunk_alert.proto does not exist
Removing internalapi/central/collector.pb.go because internalapi/central/collector.proto does not exist
```

2024-04-17 07:55 UTC, mtodor commented
@dashrews78 Nice catch! Tnx! I had two wrong ones:
```
find ./proto/internalapi/sensor -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/internalapi\/central;sensor";/' {}
find ./proto/internalapi/wrapper -type f -name '*.proto' | xargs -I {} sed -i "" 's/option.*go_package.*/option go_package = ".\/internalapi\/central;wrapper";/' {}
```
Classical copy/paste mistake! 😞 

@janisz Yes, it works with V2. I have added info in the migration plan doc.

2024-04-17 09:53 UTC, dashrews78 approved these changes

2024-04-17 11:10 UTC, janisz approved these changes

2024-04-17 14:33 UTC, janisz approved these changes

2024-04-17 15:22 UTC, rhybrillou approved these changes

2024-04-17 16:54 UTC, mtodor commented
/test gke-ui-e2e-tests

2024-04-18 07:17 UTC, merged