fix: scan latest with roxctl
stackrox/stackrox pull request #11131
Opened 2024-05-16 11:14 UTC by janisz

## Description

Currently we scan images based on their just builded tag. This results in many security issues as every issues if reported for every commit (and nightly tag). This PR changes scanning logic to scan the latest tag if we are on master (as it should be just pushed) and keep tags if not on master. To reduce the noise this PR skips uploading sarif for nightly builds.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

Hard to test as we need to be on master to scan.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2024-05-16 11:28 UTC, stehessel approved these changes

2024-05-16 12:10 UTC, stehessel requested changes
Actually I think some of the images don't have a `latest` tag. See for example https://quay.io/repository/rhacs-eng/stackrox-operator?tab=tags.

2024-05-16 14:59 UTC, janisz commented
@stehessel Good point. I keep operator as it was before and `latest` for other `master` runs

2024-05-17 01:33 UTC, stehessel commented
@janisz Could you please go through the other images as well? I didn't check all of them, but https://quay.io/repository/rhacs-eng/scanner-v4?tab=tags doesn't seem to have `latest` either.

2024-07-15 15:43 UTC, closed without merging