Tolerate unset env var in export_central_basic_auth_creds.
stackrox/stackrox pull request #11455
Opened 2024-06-10 12:36 UTC by porridge

## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

TODO(replace-me)  
Use this space to explain **how you validated** that **your change functions exactly how you expect it**.
Feel free to attach JSON snippets, curl commands, screenshots, etc. Apply a simple benchmark: would the information you
provided convince any reviewer or any external reader that you did enough to validate your change.

It is acceptable to assume trust and keep this section light, e.g. as a bullet-point list.

It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change only.  
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case you are
responsible for the change after it gets merged which includes reverting, fixing, etc. Make sure you validate the change
ASAP after it gets merged or explain in PR when the validation will be performed.  
Explain here why you skipped testing in case you did so.

Have you created automated tests for your change? Explain here which validation activities you did manually and why so.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2024-06-10 12:36 UTC, porridge commented
/test ?

2024-06-10 12:37 UTC, porridge commented
/test ocp-4-15-nongroovy-e2e-tests
/test gke-nongroovy-e2e-tests

2024-06-11 05:55 UTC, porridge commented
/test gke-nongroovy-e2e-tests
/test ocp-4-15-nongroovy-e2e-tests

2024-06-11 12:13 UTC, porridge commented
/test gke-nongroovy-e2e-tests
/test ocp-4-15-nongroovy-e2e-tests

2024-06-11 15:35 UTC, porridge commented
/test gke-nongroovy-e2e-tests
/test ocp-4-15-nongroovy-e2e-tests

2024-06-11 17:39 UTC, porridge commented
/test gke-nongroovy-e2e-tests
/test ocp-4-15-nongroovy-e2e-tests

2024-06-12 06:41 UTC, porridge commented
/test gke-nongroovy-e2e-tests
/test ocp-4-15-nongroovy-e2e-tests

2024-06-12 08:41 UTC, porridge commented
/test gke-nongroovy-e2e-tests
/test ocp-4-15-nongroovy-e2e-tests

2024-06-12 10:33 UTC, porridge commented
/test ocp-4-15-nongroovy-e2e-tests

2024-06-12 12:31 UTC, porridge commented
/test ocp-4-15-nongroovy-e2e-tests

2024-06-12 14:25 UTC, porridge commented
/retest-times 10 gke-nongroovy-e2e-tests
/retest-times 10 ocp-4-15-nongroovy-e2e-tests

2024-06-12 14:27 UTC, porridge commented
/test ocp-4-15-nongroovy-e2e-tests
/test gke-nongroovy-e2e-tests

2024-06-12 17:19 UTC, gavin-stackrox requested changes
I'd like to see that `nit:` changed throughout.

2024-06-12 17:22 UTC, porridge commented on tests/e2e/run.sh
> +    if [[ ${ORCHESTRATOR_FLAVOR:-} = openshift ]]; then
Done, PTAL

2024-06-12 17:23 UTC, porridge commented
/test ocp-4-15-nongroovy-e2e-tests

2024-06-12 17:27 UTC, gavin-stackrox approved these changes

2024-06-12 21:28 UTC, porridge commented
/test ocp-4-12-scanner-v4-tests

2024-06-12 22:43 UTC, gavin-stackrox commented
CI looks good. Will merge.

2024-06-12 23:26 UTC, merged