Add eks and kops for dependabot e2e labels
stackrox/stackrox pull request #1260
Opened 2022-04-12 10:34 UTC by janisz

## Description

Add labels to run on different configurations.
Refs: https://github.com/stackrox/stackrox/pull/1223

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [stackrox/openshift-docs](https://github.com/stackrox/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

2022-04-12 14:23 UTC, gavin-stackrox requested changes

2022-04-13 00:36 UTC, gavin-stackrox commented on .github/dependabot.yaml
>        - "dependencies"
The upgrade test bounces between versions and runs a test not covered elsewhere.
```suggestion
      - "ci-upgrade-tests"
      - "dependencies"
```

2022-04-13 00:36 UTC, gavin-stackrox approved these changes

2022-04-13 08:10 UTC, janisz commented
@gavin-stackrox should we remove kops from circleci config then?

2022-04-13 14:53 UTC, gavin-stackrox commented
> @gavin-stackrox should we remove kops from circleci config then?

I don't see any kops in there

2022-04-13 18:32 UTC, msugakov approved these changes

2022-04-13 18:33 UTC, msugakov commented
For the history. This relates to https://srox.slack.com/archives/C0321S70YK1/p1649759029278849

2022-04-14 09:04 UTC, merged