Mc/crs 50 helm chart
stackrox/stackrox pull request #12713
Opened 2024-09-16 22:41 UTC by mclasmeier

### Description

change me!

### User-facing documentation

- [ ] CHANGELOG is updated **OR** update is not needed
- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests

#### How I validated my change

change me!

2024-10-11 09:49 UTC, mclasmeier commented
/retest

2024-11-12 17:56 UTC, mclasmeier commented
/test all

2024-11-12 19:10 UTC, mclasmeier commented
/test all

2024-11-12 22:18 UTC, mclasmeier commented
/test all

2024-11-12 23:34 UTC, mclasmeier commented
/test all

2024-11-13 08:33 UTC, mclasmeier commented
/test all

2024-11-13 13:55 UTC, mclasmeier commented
/test all

2024-11-13 20:53 UTC, mclasmeier commented
/test all

2024-11-13 23:51 UTC, mclasmeier commented
/test all

2024-11-14 12:59 UTC, mclasmeier commented
/test all

2024-11-14 14:15 UTC, mclasmeier commented
/retest

2024-11-14 16:02 UTC, mclasmeier commented
/retest

2024-11-14 18:29 UTC, mclasmeier commented
/test all

2024-11-14 21:47 UTC, mclasmeier commented
/retest

2024-11-14 21:50 UTC, mclasmeier commented
/retest

2024-11-20 07:57 UTC, mclasmeier commented
/retest

2024-11-21 20:27 UTC, mclasmeier commented
/test all

2024-11-22 01:08 UTC, mclasmeier commented
/test all

2024-11-22 20:15 UTC, mclasmeier commented
/test all

2024-11-22 22:02 UTC, mclasmeier commented
/test all

2024-11-26 11:48 UTC, vikin91 commented
Please ping us when this is no longer a draft and is ready for review.

2024-12-11 11:51 UTC, mclasmeier commented
/test all

2024-12-11 13:12 UTC, mclasmeier commented
/test all

2024-12-11 13:32 UTC, mclasmeier commented
/test all

2025-01-02 06:55 UTC, porridge requested changes
A bunch of questions and nitpicks inline.
In particular I don't understand how the CRS file is being loaded 🤔 
I see the example mentions a file path, and then it's being treated like the file content.. what am I missing?

2025-01-02 06:55 UTC, porridge commented on CHANGELOG.md
> +- ROX-26088: Implemented Cluster Registration Secrets (CRS) as a successor to init bundles for registering Secured Clusters.
```suggestion
- ROX-26088: Introduced Cluster Registration Secrets (CRS) as a successor to init bundles for registering Secured Clusters.
```

2025-01-02 06:55 UTC, porridge commented on deploy/common/k8sbased.sh
> +        if [[ "${ROX_DEPLOY_SENSOR_WITH_CRS:-}" == "true" ]]; then
I don't get this:
```
      if [[ "${ROX_DEPLOY_SENSOR_WITH_CRS:-}" == "true" ]]; then
         ...
      else
        if [[ "${ROX_DEPLOY_SENSOR_WITH_CRS:-}" == "true" ]]; then
```
Am I missing something or is this logic broken?

2025-01-02 06:55 UTC, porridge commented on deploy/common/k8sbased.sh
> +        helm lint --set ca.cert=PLACEHOLDER_FOR_LINTING "${helm_chart}" -n "${sensor_namespace}" "${helm_args[@]}" "${extra_helm_config[@]}"
Does this last command really also need the placeholder? We're about to call `helm upgrade` for real with the same args but without placeholder, so we'd better make sure the lint passes without the placeholder here as well, right?

2025-01-02 06:55 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +> registration secret (CRS)").
As a user I'd be confused without further hints on whether I should skip or not.

2025-01-02 06:55 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +    [ -f <path to cluster-init-bundle.yaml> | -f crs.file=<path to crs.yaml> ] \
`-f var=value` - is this valid?

My helm help shows just:

```
  -f, --values strings                             specify values in a YAML file or a URL (can specify multiple)
```

Should this have been `--set`?

2025-01-02 06:55 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +{{- if kindIs "string" $crsFile -}}
What if a user sets this to `42`? 🙈

2025-01-02 06:55 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +    {{ include "srox.fail" "A cluster registration secret cannot be used with manually managed (helmManaged=false) clusters." }}
We are introducing an implicit binding with `_securedClusterCertRefresh` implementation... If `_securedClusterCertRefresh` ever ended up false for some reason other than "manually managed" - this message would be super confusing...
Perhaps we should rename `_securedClusterCertRefresh`? 🤔

2025-01-02 06:55 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{/* FAIL ASSERT */}}
Is this a TODO?

2025-01-02 06:55 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
> +          - kubernetes-sensor
```suggestion
        - kubernetes-sensor
```

2025-01-02 06:55 UTC, porridge commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/crs.test.yaml
> +  # - name: "Trying with no bundle"
Why commented out (here and below)?

2025-01-02 10:13 UTC, mclasmeier commented on deploy/common/k8sbased.sh
> +        if [[ "${ROX_DEPLOY_SENSOR_WITH_CRS:-}" == "true" ]]; then
The lower fragment is outdated. Removed it. Thanks!

2025-01-02 11:04 UTC, mclasmeier commented on deploy/common/k8sbased.sh
> +        helm lint --set ca.cert=PLACEHOLDER_FOR_LINTING "${helm_chart}" -n "${sensor_namespace}" "${helm_args[@]}" "${extra_helm_config[@]}"
Oh, thanks, yes, I have removed the last one.

2025-01-02 11:10 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +    [ -f <path to cluster-init-bundle.yaml> | -f crs.file=<path to crs.yaml> ] \
No, `-f` is correct. See e.g. https://helm.sh/docs/helm/helm_install

This feature is key for unifying the different formats: one for `helm install` and one for the the operator. The CRS is indeed just a single K8s secret manifest, but it is not injected into the Helm values in a way that it is polluting the global namespace.

2025-01-02 11:11 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{/* FAIL ASSERT */}}
Yes, will resolve this in a follow-up commit.

2025-01-02 12:40 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +> registration secret (CRS)").
I have elaborated slightly in commit 3755e1ea2099cdbba868c0cbc1e7c7f8ab601f6c.

2025-01-02 12:49 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +{{- if kindIs "string" $crsFile -}}
Ok, I will add a branch for catching `$crsFile == 42`.
🤔 

OTOH, I would need to do the same for other integers as well, for consistency reasons, WDYT?

jk.

Seems to work as expected in its current shape:
```
helm upgrade --install -n "$NS" \
    ... \
    --set clusterName=foo \
    --set centralEndpoint="$CENTRAL_ENDPOINT" \
    --set-file crs.file=42 \
    stackrox-secured-cluster-services ./stackrox-secured-cluster-services-chart
Release "stackrox-secured-cluster-services" does not exist. Installing it now.
Error: failed parsing --set-file data: open 42: no such file or directory
```

The whole file-reading is done by the `helm` command itself.

2025-01-02 13:01 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +    {{ include "srox.fail" "A cluster registration secret cannot be used with manually managed (helmManaged=false) clusters." }}
Cc: @vlad

Hmm, well, I would prefer to not go into renaming this -- at least not as part of this PR.
For this change (CRS) I need to depend on `_securedClusterCertRefresh`, because this controls the creation of the init containers, which we need for CRS as well.

And due to https://github.com/stackrox/stackrox/blob/3755e1ea2099cdbba868c0cbc1e7c7f8ab601f6c/image/templates/helm/shared/templates/_certrefresh.tpl the value of `_securedClusterCertRefresh` is (in the current version of the code...) guaranteed to be  `true` if and only if `._rox.managedBy != "MANAGER_TYPE_MANUAL"`.

2025-01-02 13:53 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/crs.test.yaml
> +  # - name: "Trying with no bundle"
Let me just say, I have iterated on it in 6ffe1349c7b78ff82d877941e334214093b84b21.
The two tests are now enabled (in modified form) and this required minor refactoring in the `_init.htpl` to properly catch the case of an init bundle and a CRS being provided at the same time.

2025-01-02 13:54 UTC, mclasmeier commented
> A bunch of questions and nitpicks inline. In particular I don't understand how the CRS file is being loaded 🤔 I see the example mentions a file path, and then it's being treated like the file content.. what am I missing?

This a feature of the helm CLI, maybe poorly documented.

2025-01-06 07:31 UTC, mclasmeier commented
/retest

2025-01-08 12:15 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +    [ -f <path to cluster-init-bundle.yaml> | -f crs.file=<path to crs.yaml> ] \
On that page I can see `--set-file` being used this way, not `-f` (a.k.a. `--values`):
````
$ helm install --set-file my_script=dothings.sh myredis ./redis
```

Are you saying the semantics of `-f` becomes that of `--set-file` if the parameter contains an `=` character?
Even then, I think we're better off providing the documented flag rather than this undocumented trick, WDYT?

2025-01-08 12:48 UTC, porridge commented on deploy/common/k8sbased.sh
> +      if [[ -z "$CI" && -z "${ROX_DEPLOY_SENSOR_WITH_CRS:-}" && "${secured_cluster_chart_supports_crs}" == "true" ]]; then
Why disable this in CI?

2025-01-08 12:48 UTC, porridge commented on deploy/common/k8sbased.sh
> +        if [[ "${ROX_DEPLOY_SENSOR_WITH_CRS:-}" == "true" ]]; then
I don't see any change.
![image](https://github.com/user-attachments/assets/bdda416f-31ac-41f2-b43d-c7a057912201)

2025-01-08 12:48 UTC, porridge commented on deploy/common/k8sbased.sh
> +        helm lint --set ca.cert=PLACEHOLDER_FOR_LINTING "${helm_chart}"
While at it, can you maybe add an `echo` before each `helm lint` line to make it easier to understand what's going on when viewing the CI logs?

2025-01-08 12:48 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +> **NOTE**: Beginning with StackRox/ACS 4.6 there exists a modern alternative to init bundles which goes
`[<- if .FeatureFlags.ROX_CLUSTER_REGISTRATION_SECRETS >]`
here and below?

2025-01-08 12:48 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +    [ -f <path to cluster-init-bundle.yaml> | -f crs.file=<path to crs.yaml> ] \
To make this crystal clear, I think this should say:
```suggestion
    [ -f <path to cluster-init-bundle.yaml> | --set-file crs.file=<path to crs.yaml> ] \
```
Like in the snippet you pasted below in response to my comment about 42.

2025-01-08 12:48 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +{{- if kindIs "string" $crsFile -}}
OK, I was confused about whether `._rox.crs.file` is the file path or file content. Now it's obvious to me it's the content. And if the path was garbage then the above error message seems good enough.

The question is: the type of `._rox.crs.file` guaranteed to be only a string or be unset? I'd like to make sure that the error message makes sense if the user feeds in a file that contains garbage. For example what happens if the file contains just ASCII digits? Will it get ignored by this conditional or not?

2025-01-08 12:48 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{- $crsManifest := $crsFile | fromYaml -}}
And related to the above, what happens if the YAML fails to parse? Will this line abort with a helpful message?

2025-01-08 12:48 UTC, porridge commented on image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
>        {{- if ._rox._securedClusterCertRefresh }}
Can you change this to
```suggestion
      {{- if or ._rox._securedClusterCertRefresh ._rox.crs._enabled }}
```

And then either drop the `  {{- if not ._rox._securedClusterCertRefresh -}}` check in `_init.tpl.htpl` or replace it with with an explicit check of managed_by...? 🤔

2025-01-08 15:31 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +> registration secret (CRS)").
Does it seem sufficient to you?

2025-01-08 16:11 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +    [ -f <path to cluster-init-bundle.yaml> | -f crs.file=<path to crs.yaml> ] \
Oh my...
I had this confusion in my mind that `-f` is the short form for `--set-file` 🤦 
`-f` is wrong, `--set-file` is correct, fixed in eb9456d39f5bf3856629f4628e4848a6d84d3279.

2025-01-08 16:21 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +{{- if kindIs "string" $crsFile -}}
Alright, so, first test:
I have a file named '1' which contains only a '2' (no line break). Attempting to install using `--set-file crs.file=1` produces:
```
FATAL ERROR:
Invalid cluster registration secret manifest: missing field data.crs in CRS secret
manifest
```

2025-01-08 16:35 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +{{- if kindIs "string" $crsFile -}}
Another test:
I have tried `--set-file crs.file=/bin/ls` and this was treated as if an empty file had been provided, because the return value of `fromYaml` in this case is a dict of the form
```
{
  "Error": "error message"
}
```

I have added a few lines in commit 671937b6fe0420a3056d7ad33a7f4c5a01acfc54 to catch this case and now the error message of `helm install --set-file=/bin/ls` looks like this:

```
FATAL ERROR:
Cluster registration secret file is invalid: error converting YAML to JSON: yaml:
invalid trailing UTF-8 octet
```

Thanks!

2025-01-08 16:45 UTC, mclasmeier commented on deploy/common/k8sbased.sh
> +        helm lint --set ca.cert=PLACEHOLDER_FOR_LINTING "${helm_chart}"
Done in commit 60bcfe45b94fc929945cdfcba0d885af0971e79b.

2025-01-08 16:50 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +> **NOTE**: Beginning with StackRox/ACS 4.6 there exists a modern alternative to init bundles which goes
Agreed, done in 20a8e9b8995a2f835ddc9cf53d3afe150bf0b198.

2025-01-08 16:50 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +    [ -f <path to cluster-init-bundle.yaml> | -f crs.file=<path to crs.yaml> ] \
done

2025-01-08 16:51 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{- $crsManifest := $crsFile | fromYaml -}}
Added extra lines for improved error reporting in the parsing failure case.

2025-01-08 16:52 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
>        {{- if ._rox._securedClusterCertRefresh }}
CRS without `_securedClusterCertRefresh` does not make sense, in my opinion. CRS requires the init containers. And these are controlled by `_securedClusterCertRefresh`. So, as I see it, CRS depends on `_securedClusterCertRefresh`.
Or do I misunderstand?
WDYT?

2025-01-10 09:32 UTC, mclasmeier commented
/retest

2025-01-13 13:07 UTC, porridge approved these changes
A bunch of nitpicks, and a question about `$CI`, but nothing blocking.

2025-01-13 13:07 UTC, porridge commented on deploy/common/k8sbased.sh
> +        local api_resp
We already declare `api_resp` on line 677. Seems like we should either:
- move that definition to line ~707 and remove this one, or
- move that definition to line ~712

2025-01-14 05:27 UTC, mclasmeier commented on deploy/common/k8sbased.sh
> +        local api_resp
72f0f983442455b50a8522b328d196998eaefe76

2025-01-14 05:27 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{- end -}}
16ae1a33d824beaf23cd7897891df8c152d2b4d3

2025-01-14 05:27 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/crs.test.yaml
> +              crs.platform.stackrox.io/expires-at: "2025-11-12T20:47:00Z"
Yes, this is just for the user. However, see comment in ef060285f39a37c9ba40a94b08d1961a479ff484

2025-01-14 05:27 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/crs.test.yaml
> +            crs: ZXlKRFFYTWlPbHNpTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0WEc1TlNVbEVVRlJEUTBGcFYyZEJkMGxDUVdkSlVVY3JaekozTjNwcFZuSkpjRTVqZG1oQ01ucHBSV3BCVGtKbmEzRm9hMmxIT1hjd1FrRlJjMFpCUkVGd1
Done in ef060285f39a37c9ba40a94b08d1961a479ff484

2025-01-14 08:09 UTC, mclasmeier commented
/retest

2025-01-14 09:04 UTC, mclasmeier commented
@porridge I have added c35dac3711 -- let's see what CI thinks.

2025-01-14 11:16 UTC, mclasmeier commented
/retest

2025-01-14 11:29 UTC, mclasmeier commented
/retest

2025-01-14 11:43 UTC, mclasmeier commented
/retest

2025-01-14 11:54 UTC, mclasmeier commented
/retest

2025-01-14 14:55 UTC, mclasmeier commented
/retest

2025-01-15 07:34 UTC, mclasmeier commented
/retest

2025-01-16 11:04 UTC, mclasmeier commented on deploy/common/k8sbased.sh
> +        local api_resp
Will mark this as resovled!

2025-01-16 11:07 UTC, mclasmeier commented
> Please ping us when this is no longer a draft and is ready for review.

It's ready to be merged. But I don't remember why you raised interest in this specific PR -- maybe you were automatically assigned as reviewers? In any case, this is just about the Helm changes for CRS, so I don't think you need to care about this one.

2025-01-16 11:07 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{- end -}}
Will mark this as resolved!

2025-01-16 11:08 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/crs.test.yaml
> +              crs.platform.stackrox.io/expires-at: "2025-11-12T20:47:00Z"
Will mark this as resolved!

2025-01-16 11:08 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/crs.test.yaml
> +            crs: ZXlKRFFYTWlPbHNpTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0WEc1TlNVbEVVRlJEUTBGcFYyZEJkMGxDUVdkSlVVY3JaekozTjNwcFZuSkpjRTVqZG1oQ01ucHBSV3BCVGtKbmEzRm9hMmxIT1hjd1FrRlJjMFpCUkVGd1
Will mark this as resolved!

2025-01-16 11:10 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +{{- if kindIs "string" $crsFile -}}
Will mark this as resolved!

2025-01-16 11:10 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/crs.test.yaml
> +  # - name: "Trying with no bundle"
Will mark this as resolved!

2025-01-16 11:11 UTC, mclasmeier commented on deploy/common/k8sbased.sh
> +      if [[ -z "$CI" && -z "${ROX_DEPLOY_SENSOR_WITH_CRS:-}" && "${secured_cluster_chart_supports_crs}" == "true" ]]; then
Will mark this as resolved!

2025-01-16 11:11 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +    [ -f <path to cluster-init-bundle.yaml> | -f crs.file=<path to crs.yaml> ] \
Will mark this as resolved!

2025-01-16 11:11 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
>        {{- if ._rox._securedClusterCertRefresh }}
Will mark this as resolved!

2025-01-16 11:12 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/README.md.htpl
> +> registration secret (CRS)").
Will mark this as resolved!

2025-01-16 11:12 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{/* FAIL ASSERT */}}
Will mark this as resolved!

2025-01-16 11:14 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +    {{ include "srox.fail" "A cluster registration secret cannot be used with manually managed (helmManaged=false) clusters." }}
Will mark this as resolved!

2025-01-16 12:42 UTC, mclasmeier commented
/retest

2025-01-16 14:27 UTC, vladbologa commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{- if not ._rox._securedClusterCertRefresh -}}
nit: the name of _securedClusterCertRefresh could be improved now that it's also used here, because the connection between CRS & secured cluster cert refresh might not be that obvious.

Can be done in a follow-up though, don't want to stall these PRs.

2025-01-16 14:35 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{- if not ._rox._securedClusterCertRefresh -}}
Agreed, will add this to my list of follow-up changes.

2025-01-16 16:37 UTC, vikin91 commented
> > Please ping us when this is no longer a draft and is ready for review.
> 
> It's ready to be merged. But I don't remember why you raised interest in this specific PR -- maybe you were automatically assigned as reviewers? In any case, this is just about the Helm changes for CRS, so I don't think you need to care about this one. @vikin91

Yes, I was pinged as a reviewer. As I am no longer in the reviewer list then there is no need to worry about that comment :)

2025-01-16 18:24 UTC, merged