chore(CI): Ignore compliance container in pod restarts check
stackrox/stackrox pull request #12815
Opened 2024-09-26 10:52 UTC by mtodor

### Description

This PR is disabling the Pod Restarts check for the collector compliance container. After https://issues.redhat.com/browse/ROX-26311 - is resolved, we can revisit the ignore pattern.

We had such a pattern in the past, but after some compliance code refactoring, it became obsolete because the error message was changed (from `error ..` to `Error ..`).

I have "reused" that pattern slot and modified matching logging to also match `gke` tests.
I also fixed the `bats` test (btw. they are broken on Master, at least for me).

### User-facing documentation

- [x] CHANGELOG is updated **OR** update is not needed
- [x] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [x] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [x] modified existing tests

#### How I validated my change

Executed `bats` test locally.

2024-09-26 13:11 UTC, stehessel commented on scripts/ci/logcheck/check-restart-logs.sh
> +# TODO: revisit (update/delete) "compliance-previous" pattern after "ROX-26311" is resolved.
```suggestion
# TODO(ROX-26311): revisit (update/delete) "compliance-previous" pattern after "ROX-26311" is resolved.
```
Let's mention in the ticket to revisit this comment once the ticket is resolved.

2024-09-26 13:11 UTC, stehessel approved these changes

2024-09-26 15:19 UTC, vikin91 approved these changes
The change looks good. I have not tested it, but I see that the fixture was used to cover this.

2024-09-27 08:03 UTC, porridge requested changes
LGTM overall, but I don't understand your comment about fixing bats tests. In fact they seem [broken *after* your change](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12815/pull-ci-stackrox-stackrox-master-shell-unit-tests/1839292412418068480#1:build-log.txt%3A140).

2024-09-27 12:13 UTC, mtodor commented on scripts/ci/logcheck/check-restart-logs.sh
> +# TODO(ROX-26311): revisit (update/delete) "compliance-previous" pattern after "ROX-26311" is resolved.
@porridge I could remove this comment, and we can rely on `"comment": "ROX-26311: compliance is not able to establish connection with sensor",` - in JSON. Would that be ok?

The problem is that JSON format does not support comments. (at least to my knowledge)

2024-09-27 12:23 UTC, porridge commented on scripts/ci/logcheck/check-restart-logs.sh
> +# TODO(ROX-26311): revisit (update/delete) "compliance-previous" pattern after "ROX-26311" is resolved.
Would it be possible to change that to `"comment": "TODO(ROX-26311): compliance is not able to establish connection with sensor",` ?

2024-10-01 16:02 UTC, vikin91 commented
There is a fix candidate - #12859 - for the issue that lead to excluding the checks of compliance restarting in this PR.

2024-10-02 07:19 UTC, vikin91 commented
Please, let's hold merging this. I have just merged the https://github.com/stackrox/stackrox/pull/12859. The fix is non-trivial to validate outside of CI, so I would appreciate if we could keep the alerts about compliance crashing in CI.

2024-10-02 08:57 UTC, mtodor commented
/test ocp-4-12-scanner-v4-tests

2024-10-08 11:33 UTC, mtodor commented
Moved to `draft` in favor of #12815 - will close it after the merge of another PR.

2024-10-14 12:04 UTC, closed without merging