ROX-24945: Add per-container rate limit to collector runtime config
stackrox/stackrox pull request #13228
Opened 2024-11-05 10:15 UTC by Stringy

### Description

Adds per-container rate limit to Collector runtime configuration. This primarily controls the number of connections Collector will report, as a release valve when external IPs are enabled. Afterglow and batching that currently exist within Collector are not sufficient when External IPs are enabled (since afterglow can only limit duplicate connections)

### User-facing documentation

- [ ] CHANGELOG is updated **OR** update is not needed
- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests

#### How I validated my change

change me!

2024-11-13 12:18 UTC, Stringy commented
/retest

2024-11-18 10:50 UTC, ovalenti requested changes
I think that we should remove the Collector version bump before getting this merged to avoid making stackrox/stackrox point to an ephemeral commit.

2024-11-18 10:52 UTC, ovalenti commented on COLLECTOR_VERSION
> +3.20.x-44-g3216b034e6
Oh ! I missed this comment :sweat_smile: sorry

The good thing is that we agree on this point.

2024-11-18 14:00 UTC, Stringy commented
> I think that we should remove the Collector version bump before getting this merged to avoid making stackrox/stackrox point to an ephemeral commit.

@ovalenti - Done

2024-11-18 14:01 UTC, ovalenti approved these changes

2024-11-18 15:32 UTC, merged