ROX-18384: removes the slim collector distinction
stackrox/stackrox pull request #13350
Opened 2024-11-15 14:34 UTC by Stringy

### Description

change me!

### User-facing documentation

- [ ] CHANGELOG is updated **OR** update is not needed
- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests

#### How I validated my change

change me!

2024-12-04 15:25 UTC, Stringy commented
/test all

2024-12-17 14:54 UTC, Stringy commented
/test all

2024-12-18 13:04 UTC, Stringy commented
/test all

2024-12-19 09:45 UTC, vikin91 reviewed
How nice that we are getting rid of that :) This is a substantial change and the most important part here would be to test all installation methods. I remember that when we worked on the flavors, we had a matrix where we tested the following:

```
for op in (fresh-install, upgrade)
   for install-method in (manifests, helm, operator)
        deploy/upgrade ACS()
```
It would be great if we could test those here as well.

We should also not forget about:
- Downstream changes in CPaaS (if needed) (in case we still plan to use it) 
- Manual upgrade instructions for customers who purely rely on generating manifests and `kubectl apply -f - ` them.

In the meantime, I am queueing this for a proper review.

2024-12-19 11:07 UTC, Stringy commented
> It would be great if we could test those here as well.

Yeah absolutely. I intend to perform most of this testing in parallel to the reviews, as my initial testing of helm & operator upgrading between master and this branch has been largely successful. I'll keep track of results in the main PR description.

2025-01-03 12:26 UTC, Stringy commented
I have just finished doing all the tests from the suggested test matrix, and all tests have succeeded. Slim mode is ignored during upgrade, resulting in collector images that do not have the `-slim` suffix.

2025-01-08 18:38 UTC, msugakov commented on operator/config/manager/manager.yaml
> +        - name: RELATED_IMAGE_COLLECTOR
I think, this rename `RELATED_IMAGE_COLLECTOR_SLIM`+`RELATED_IMAGE_COLLECTOR_FULL` -> `RELATED_IMAGE_COLLECTOR` is sensible and is an improvement @tommartensen also asked about in https://github.com/stackrox/stackrox/pull/13748, but I'm a bit uneasy about this change.

These `RELATED_IMAGE_*` environment variables are filled with images pullspecs containing digests (i.e. pinned precise image the operator should deploy for each operand) during the downstream builds (and will also be populated during Konflux builds the same way) so users don't need to worry about the existence of these variables and their contents.

We extensively went over these with @mclasmeier and @porridge for Konflux builds and it will be useful to tag them here anyway.

<details>
<summary>A side note</summary>

If we go with the rename, you'll also need to remove this conditional in the midstream setup <https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/blob/rhacs-1.0-rhel-8/distgit/containers/rhacs-operator-bundle/collect-related-images.py?ref_type=heads#L312-313> but I think dealing with collector-slim setup downstream should be part of the deal named "removal of slim collector" anyway (besides `rhacs-collector-slim` directory in that repo, there's a setup in another repo: <https://gitlab.cee.redhat.com/cpaas-products/rhacs/-/blob/main/versions/release-1.0/product.yml?ref_type=heads#L79>).

Similarly, there's some stuff on the Konflux side that we need to clean up for 4.7 or whenever this change lands (but not for 4.6), but I think it's best if we keep it with our Konflux team.

</details>

The thing is: these environment variables are overridable and hence form a contract whether we want it or not. Users may override them to deploy different versions of images or point to different repos. They shouldn't do it because we don't document that and don't advertise it (at least I wasn't able to find mentions under https://docs.openshift.com/acs/welcome/ and https://access.redhat.com/solutions/) but they technically can. Once we delete the old variables and introduce the one with the new name, users won't have their overrides applied upon the upgrade.

A quick search in GitHub and Confluence revealed these:
- https://github.com/Nanyte25/rhacs-goat/blob/main/Makefile
- https://github.com/stackrox/acs-fleet-manager/blob/cd8366e48790457ae138ff0fdcb1ddfabf5a5111/fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml#L57
- https://github.com/stackrox/acs-fleet-manager-config/blob/568e5fc3775822060b6672f7940c2a50e52fc286/acs-int-us-01/08-rhacs-operator/v4-2-2.yaml#L71
- https://spaces.redhat.com/display/StackRox/Pre-GA+ACS+Collector+for+AppSRE+cluster

My conclusions are:
1. Some users may already do this.
2. ACS CS folks have the variable names in their code and need to be informed to adjust after this new version is released.
3. If AppSRE still uses the instructions, we should inform them about the change in the new version.

If we proceed with this change, and some users intentionally override the environment variables to get a different version of Collector deployed, they will get a default one upon the upgrade. If that becomes a problem for them and they notice, they will have to update the new environment variable.
If we consider a commercial use and such a setup is reported through support as having problems around Collector, I would not be surprised if one of the first things asked will be to undo the overrides.

If some users intentionally override the environment variables to consume images from different repos than we specify upon release (our default location in the Red Hat catalog, i.e. `registry.redhat.io/advanced-cluster-security/*`), their Collector will be deployed from the Red Hat catalog or won't boot up if the image can't be pulled. Overall, the use of these variables for overriding repos is not a valid case because there are different approaches to do that (ImageDigestMirrorSet / ImageContentSourcePolicy), and so breaking such invalid case is maybe not that dramatic.

Since the contract isn't public and the use of values for overrides seems questionable, I'd vote for the rename but please make sure to inform the mentioned teams and add an item to `CHANGELOG.md` about the variable names change so that it gets to release notes and users at least may find a trace that we indeed made the change in a certain version.

2025-01-08 18:40 UTC, msugakov commented on roxctl/sensor/generate/generate.go
> +	autobool.NewFlag(c.PersistentFlags(), &generateCmd.slimCollectorP, slimCollector, "[Deprecated] this argument is ignored")
There might be a way to hide the flag so that it does not show up in `--help` but does not lead to errors when parsing the command line.

2025-01-08 19:08 UTC, msugakov commented on roxctl/sensor/generate/generate_test.go
>  			serverHasKernelSupport: false,
This `KernelSupport` thing at the time of Secured Cluster manifests _generation_ is another chunk which _could be_ cleaned up.
IIRC, the availability of Kernel Support means either the Central is connected to the internet and can reach our place for driver downloads or that there's a support package uploaded to Central.
For core_bpf Collector none of this matters and so some _generation_ code could be simplified.

Still, the old versions of `roxctl` which expect some API contract should continue working with the new Central so if there are kernel support flags they should be returned as `true`, etc.

Also, for as long as ACS versions that use collector drivers aren't deprecated, the driver download and the support package mechanisms should exist even in the new Centrals.

2025-01-09 00:12 UTC, JoukoVirtanen commented on image/templates/helm/stackrox-secured-cluster/internal/defaults/50-images.yaml.htpl
> -    fullRef: {{ ._rox.image.collector.full.fullRef }}
Do you still need `fullRef`.

2025-01-09 00:27 UTC, JoukoVirtanen commented on operator/internal/securedcluster/values/translation/translation.go
>  		case platform.ImageFlavorRegular:
Probably just use an if statement instead of a switch.

2025-01-09 01:02 UTC, JoukoVirtanen commented on ui/apps/platform/src/Containers/Clusters/ClusterEditForm.tsx
> -import { CentralEnv } from './clusterTypes'; // augmented with successfullyFetched
What is the purpose of the deletions in this file?

2025-01-09 01:06 UTC, JoukoVirtanen commented on ui/apps/platform/src/Containers/Clusters/StaticConfigurationSection.js
> -                <div className="flex flex-col">
I think @msugakov makes a good point. The UI should continue to report if secured clusters are using slim images.

2025-01-09 01:24 UTC, JoukoVirtanen commented
Ran the command 
```
git grep -i image | grep -i slim
```

There might be some results there that still need to be cleaned up.

```
.tekton/operator-bundle-pipeline.yaml:  - name: collector-slim-image-catalog-repo
.tekton/operator-bundle-pipeline.yaml:    description: Repository within the Red Hat Container Catalog where the collector slim image is pushed to during the release.
```

I think these need to be kept for now, but eventually we don't want to build the slim images for the release.

Perhaps 

`pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml`
`pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/collector-slimfull-image-overrides.test.yaml` 

can  be removed.

Other results
```
roxctl/sensor/generate/generate.go:	warningCentralEnvironmentError = "It was not possible to retrieve Central's runtime environment information: %v. Will use fallback defaults for " + mainImageRepository + " and " + slimCollector + " settings."
roxctl/sensor/getbundle/get_bundle.go:	infoDefaultingToSlimCollector = `Specified cluster is configured to use a slim collector image, hence producing deployment bundle using a slim collector image.
roxctl/sensor/util/central_env.go:	warningKernelSupportAvailableUnimplemented = `Central does not support API for checking if kernel support is available. Not using a slim collector image.
roxctl/sensor/util/central_env.go:Please upgrade Central if slim collector images shall be used.`
roxctl/sensor/util/get_bundle.go:	WarningSlimCollectorModeWithoutKernelSupport = `WARNING: The deployment bundle will reference a slim collector image, but it appears that central cannot provide kernel modules or eBPF probes.
```

`tests/roxctl/slim-collector.sh` can probably be removed.

2025-01-09 09:54 UTC, Stringy commented on ui/apps/platform/src/Containers/Clusters/StaticConfigurationSection.js
> -                <div className="flex flex-col">
I think it is safe to remove. 

The only version in which slim and full collector images are different is 4.4, which goes out of maintenance support on Jan 28, which is before 4.7 will be released. 

For all in-support versions (4.5, 4.6) the slim and full images are identical so the display of this configuration option is somewhat meaningless and is more confusing than beneficial -- it would be natural to assume that if slim mode is enabled, then the Collector might be downloading drivers and require an internet connection, but that is not the case any more. 

I think that removing it now, even if a secured cluster is on one of these versions, serves to clean up the UI and removes any confusion about the way the Collectors have been deployed.

(as a side note, I did panic a little just now when I saw we still had the support exception for 3.74, but the terms of that exception require the customer to remain on 4.5.x for the duration, so we don't need to concern ourselves with these very old secured clusters)

2025-01-09 10:22 UTC, Stringy commented on ui/apps/platform/src/Containers/Clusters/ClusterEditForm.tsx
> -import { CentralEnv } from './clusterTypes'; // augmented with successfullyFetched
This is the result of the tightly enforced linting rules in the UI code, which disallows unused code.

2025-01-09 10:29 UTC, Stringy commented
@JoukoVirtanen 

```
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/collector-slimfull-image-overrides.test.yaml
```
slim-collector.test.yaml has been updated to test that slim mode is ignored and the other file tests that image overrides work correctly, so I think they should stay.

Similarly `tests/roxctl/slim-collector.sh` has also been updated to test that slim mode is ignored.

2025-01-09 13:18 UTC, msugakov commented on ui/apps/platform/src/Containers/Clusters/StaticConfigurationSection.js
> -                <div className="flex flex-col">
Sounds good. Let's remove the UI.
It's worth a note though that there might be even older Secured Clusters in the wild connected to the new Central and that'll be a kind-of small regression for them but if this helps nudge users to upgrade, it's a benefit.

2025-01-09 13:40 UTC, Stringy commented on roxctl/sensor/generate/generate_test.go
>  			serverHasKernelSupport: false,
I think all currently supported versions do not require the kernel support check, or the driver downloads / support package mechanism, so I think we're in a good place to remove them. I'll do this in a follow up PR.

2025-01-15 11:25 UTC, Stringy commented on roxctl/sensor/generate/generate.go
> +	autobool.NewFlag(c.PersistentFlags(), &generateCmd.slimCollectorP, slimCollector, "[Deprecated] this argument is ignored")
I've finally been able to properly test this scenario and it works. So I think I can revert the changes here and just update the help text as you've suggested.

2025-01-16 10:14 UTC, Stringy commented
/retest

2025-01-16 16:22 UTC, janisz commented on image/templates/helm/stackrox-secured-cluster/internal/cluster-config.yaml.tpl
> +    slimCollector: false
Do we need this line?
```suggestion
```

2025-01-16 20:54 UTC, pedrottimark commented
@Stringy The deleted lines in ui files make sense. For the 5 files out of 50 total, I approve subset by this comment.

2025-01-23 08:59 UTC, mclasmeier commented on CHANGELOG.md
> +      to override Collector images should either use the new environment variable or use other image override mechanisms for your chosen installation method.
Just for my understanding, we are talking here about overwriting them during operator runtime. Is this something that we ... officially support?

2025-01-24 10:42 UTC, erthalion reviewed
Overall looks good, thanks! I've got only a couple of nitpicks, and agree with other reviewers that it would be good to have a comprehensive description about backward compatibility at the component level. E.g. what will happen if someone is using the operator and do not configure slim image, the same with explicit slim image, what happens using helm, etc. To my understanding the main difference now is that in some places `slimMode` was removed, in some other it's still present but the value is ignored, is that correct?

2025-01-24 18:16 UTC, JoukoVirtanen commented on ui/apps/platform/src/Containers/Clusters/StaticConfigurationSection.js
> -                <div className="flex flex-col">
Since versions with slim collectors are no longer supported, it is fine to remove from the UI.

2025-01-24 19:15 UTC, JoukoVirtanen commented
Keeping the tests for slim collector is fine, but what about these occurrences
```
roxctl/sensor/generate/generate.go:	warningCentralEnvironmentError = "It was not possible to retrieve Central's runtime environment information: %v. Will use fallback defaults for " + mainImageRepository + " and " + slimCollector + " settings."
roxctl/sensor/getbundle/get_bundle.go:	infoDefaultingToSlimCollector = `Specified cluster is configured to use a slim collector image, hence producing deployment bundle using a slim collector image.
roxctl/sensor/util/central_env.go:	warningKernelSupportAvailableUnimplemented = `Central does not support API for checking if kernel support is available. Not using a slim collector image.
roxctl/sensor/util/central_env.go:Please upgrade Central if slim collector images shall be used.`
roxctl/sensor/util/get_bundle.go:	WarningSlimCollectorModeWithoutKernelSupport = `WARNING: The deployment bundle will reference a slim collector image, but it appears that central cannot provide kernel modules or eBPF probes.
```

2025-01-27 09:52 UTC, Stringy commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml
> +      container(.daemonsets.collector; "collector") | .imagePullPolicy | assertThat(. == "IfNotPresent")
For full images, pulling every time was useful to pick up new kernel drivers but now that we're on core-bpf we can revert back to if-not-present since there's only one driver

2025-01-28 09:43 UTC, Stringy commented on central/clusters/zip/zip.go
> -		slimCollector = *params.SlimCollector
I think it needs to be kept so that the new version of roxctl can still communicate with older centrals

2025-01-28 09:51 UTC, Stringy commented on image/templates/helm/stackrox-secured-cluster/internal/cluster-config.yaml.tpl
> +    slimCollector: false
My understanding is that this backwards compatibility is required for upgrading from old installations (which use slim collectors) to this version or newer which doesn't.

With that in mind, what I've hopefully achieved here is that the slim collector setting is either ignored _or_ translated when upgrading. As a result, the setting is kept in the charts and elsewhere, but is set to false for new installations and removed from docs etc since it becomes an internal-only setting (which can be fully removed after 4.6 goes out of support I think)

My testing has indicated so far that this works for old clusters configured to use slim collector

The reference to it alongside pullPolicy in the readme is definitely not needed though (pullPolicy is now Always) so I'll fix that.

2025-01-28 10:36 UTC, Stringy commented on CHANGELOG.md
> +      to override Collector images should either use the new environment variable or use other image override mechanisms for your chosen installation method.
It's not supported officially via the `RELATED_*` environment variables at least. See @msugakov's comment here: https://github.com/stackrox/stackrox/pull/13350#discussion_r1907634187 

I meant to refer to official mechanisms like `image.collector.name` and `image.collector.registry` in the helm charts, for example.

2025-01-28 10:52 UTC, Stringy commented on operator/api/v1alpha1/securedcluster_types.go
> +	// Deprecated field. This field will be removed in a future release.
Based on https://github.com/stackrox/stackrox/blob/master/operator/EXTENDING_CRDS.md?plain=1#L68 it looks like these fields should never be removed, so I'll update the comment.

2025-01-28 11:47 UTC, Stringy commented on operator/internal/securedcluster/values/translation/translation.go
>  			cv.SetBoolValue("slimMode", false)
I've just run it up and looks like it's not needed - I'll remove it.

2025-01-28 11:48 UTC, Stringy commented on operator/internal/securedcluster/values/translation/translation.go
> +		if flavor == platform.ImageFlavorRegular || flavor == platform.ImageFlavorSlim {
Removed entirely - see below.

2025-01-28 11:48 UTC, Stringy commented on central/clusters/deployer_test.go
> +				s.Equal(c.expectedCollectorRef, getCollectorImage(fields), "Collector full image does not match")
Done

2025-01-28 11:50 UTC, Stringy commented on central/clusters/deployer_test.go
I'm not sure I understand - where is collector hardcoded here?

2025-01-28 12:29 UTC, mclasmeier commented on central/clusters/deployer_test.go
> +			cluster:                makeTestCluster(defaultMainImage, "example.io/collector:custom"),
Hmm, probably I am misunderstanding the test logic, but I was wondering, given that we specify a tag `custom`, that this is not showing up again in L167 below.

2025-01-28 12:49 UTC, mclasmeier commented on operator/api/v1alpha1/securedcluster_types.go
> -	//+operator-sdk:csv:customresourcedefinitions:type=spec,order=1,xDescriptors={"urn:alm:descriptor:com.tectonic.ui:select:EBPF", "urn:alm:descriptor:com.tectonic.ui:select:CORE_BPF", "urn:alm:descrip
For my understanding, this is an independent change, right?

2025-01-28 12:50 UTC, mclasmeier commented on operator/api/v1alpha1/securedcluster_types.go
> -	//+operator-sdk:csv:customresourcedefinitions:type=spec,order=2
I assume you verified that this is rendered as expected.

2025-01-28 12:53 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/flavor/testdata/helmtest/rhacs/rhacs.test.yaml
Are we also checking anywhere that irregardless of whether `slimMode` is specified by the user as `true` or `false`, the rendering succeeds and the result is the same?

Thinking out loud here, have you considered modifying the Helm code (`_init.tpl`) so that it emits a warning (?) in case the user specifies `slimMode` or tries to modify any `slimMode`-specific settings (image name, etc.).

2025-01-28 13:04 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml
> +        container(.daemonsets.collector; "collector") | .image | assertThat(. == "collector.example.com/collector:3.2.1")
Why not `-latest` as before this change?

2025-01-28 13:05 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml
>      - name: custom image tag is honored
Why is this test removed?

2025-01-28 13:07 UTC, mclasmeier commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml
> +      container(.daemonsets.collector; "collector") | .imagePullPolicy | assertThat(. == "IfNotPresent")
Maybe mention in the PR description that this is also changing the default pull policy?

2025-01-28 13:07 UTC, mclasmeier commented on pkg/renderer/kubernetes_helm_test.go
> +		CollectorImageRemote: "collector",
Ah, get it, please ignore my comment above regarding the `-latest` prefix.

2025-01-28 13:09 UTC, mclasmeier commented on roxctl/sensor/generate/generate.go
> +	autobool.NewFlag(c.PersistentFlags(), &generateCmd.slimCollectorP, slimCollector, "Use slim collector in deployment bundle. This option is ignored by Centrals newer than 4.6.")
Maybe hide the flag (accept it silently)?
How about emitting a warning in case this is provided?

2025-01-28 13:11 UTC, mclasmeier commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> +  assert_bundle_registry "$out_dir" "collector" "$(registry_from_flavor)/collector:$any_version"
Are we not handling the `development_build` case anymore, testing for `:$any_version_latest`?

2025-01-28 13:14 UTC, mclasmeier commented on tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-development.bats
> +  helm_template_secured_cluster "$out_dir" "$out_dir/rendered" "$CLUSTER_NAME"
is this required?

2025-01-28 13:15 UTC, mclasmeier commented on tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-development.bats
> +  helm_template_secured_cluster "$out_dir" "$out_dir/rendered" "$CLUSTER_NAME"
same here, looks like duplication?

2025-01-28 13:15 UTC, mclasmeier commented on tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-development.bats
> +  helm_template_secured_cluster "$out_dir" "$out_dir/rendered" "$CLUSTER_NAME"
again.

2025-01-28 13:15 UTC, mclasmeier reviewed
Couple of nits and questions.

2025-01-28 14:37 UTC, erthalion approved these changes
After few more rounds this PR looks good to me. I think it's worth waiting on an approval from @mclasmeier and then go ahead.

2025-01-29 16:44 UTC, Stringy commented on pkg/helm/charts/tests/securedclusterservices/flavor/testdata/helmtest/rhacs/rhacs.test.yaml
I have verified that rendered result is as expected, but yeah very good point, a warning would be useful, I'll add one.

2025-01-29 16:46 UTC, Stringy commented on tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-development.bats
> +  helm_template_secured_cluster "$out_dir" "$out_dir/rendered" "$CLUSTER_NAME"
Hmm probably not any more. I'll remove it!

2025-01-29 16:59 UTC, Stringy commented on operator/api/v1alpha1/securedcluster_types.go
> -	//+operator-sdk:csv:customresourcedefinitions:type=spec,order=1,xDescriptors={"urn:alm:descriptor:com.tectonic.ui:select:EBPF", "urn:alm:descriptor:com.tectonic.ui:select:CORE_BPF", "urn:alm:descrip
Yeah I suppose it is. Included here since it's related to slim images (in the sense that EBPF shouldn't be configurable any more)

2025-01-29 17:23 UTC, Stringy commented
> Keeping the tests for slim collector is fine, but what about these occurrences

@JoukoVirtanen as discussed on slack, I think we want to keep these so that roxctl can communicate and behave correctly with older Centrals (4.6 and older) when customers are using a newer version of roxctl to install older secured clusters.

Once 4.6 is out of support, these final references can be dropped.

2025-01-29 17:23 UTC, Stringy commented on tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-development.bats
> +  helm_template_secured_cluster "$out_dir" "$out_dir/rendered" "$CLUSTER_NAME"
removed

2025-01-29 17:23 UTC, Stringy commented on tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-development.bats
> +  helm_template_secured_cluster "$out_dir" "$out_dir/rendered" "$CLUSTER_NAME"
removed

2025-01-29 17:23 UTC, Stringy commented on tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-development.bats
> +  helm_template_secured_cluster "$out_dir" "$out_dir/rendered" "$CLUSTER_NAME"
removed

2025-01-29 17:24 UTC, Stringy commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml
> +      container(.daemonsets.collector; "collector") | .imagePullPolicy | assertThat(. == "IfNotPresent")
Done

2025-01-29 21:15 UTC, JoukoVirtanen approved these changes
LGTM, but get approval from others before merging.

2025-01-30 10:05 UTC, Stringy commented on operator/api/v1alpha1/securedcluster_types.go
> -	//+operator-sdk:csv:customresourcedefinitions:type=spec,order=2
Yes, absolutely. Here's a screenshot to verify that it's hidden correctly.
![Screenshot](https://github.com/user-attachments/assets/a706c510-2210-4e3d-ab67-1ec69860d53e)

2025-01-30 10:06 UTC, Stringy commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml
> +        container(.daemonsets.collector; "collector") | .image | assertThat(. == "collector.example.com/collector:3.2.1")
We've removed the -latest tag for Collector too

2025-01-30 10:07 UTC, Stringy commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/slim-collector.test.yaml
>      - name: custom image tag is honored
I felt that the cases were covered by other tests now that slim mode is removed (e.g. we have tests that cover slim mode being ignored or unset)

2025-01-30 10:27 UTC, Stringy commented on roxctl/sensor/generate/generate.go
> +	autobool.NewFlag(c.PersistentFlags(), &generateCmd.slimCollectorP, slimCollector, "Use slim collector in deployment bundle. This option is ignored by Centrals newer than 4.6.")
I've added a warning

2025-01-30 10:27 UTC, Stringy commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> +  assert_bundle_registry "$out_dir" "collector" "$(registry_from_flavor)/collector:$any_version"
No, since we no longer have -latest collector images

2025-01-31 14:32 UTC, vikin91 commented on central/clusters/deployer_test.go
> +			cluster:                makeTestCluster(defaultMainImage, "example.io/collector:custom"),
I would be `custom` for non-release builds in flavor `development` and `opensource`. For `rhacs` flavor and all release builds, we use the unified version, i.e., collector tag = main tag.

2025-01-31 15:04 UTC, vikin91 requested changes
It looks really good! I reviewed mainly the part related to sensor and flavors and skipped the UI, Helm, and operator changes.

I caught one potential mistake - I think you deprecated flavors accidentally. That is the reason why I review :x:. Could you check please?

2025-01-31 15:04 UTC, vikin91 commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> -@test "roxctl sensor generate: no overrides with collector full" {
(code line unrelated) We remove the e2e test cases for roxctl here, but we still want roxctl to work correctly with older centrals. Could we maybe add a test for that?
We could call the roxctl with params for collector slim and make sure that the error is as expected (or there is no error). I can imagine that removing all collector slim from roxctl would produce a different error than requesting bundle from central that does not support collector slim.

2025-01-31 15:04 UTC, vikin91 commented on tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-release.bats
> +  assert_components_registry "$out_dir/rendered" "quay.io/stackrox-io" "$any_version" 'collector' 'admission-controller' 'sensor'
deduplication in bats is very difficult. We always have two copies - one for development and one for release build.

2025-02-03 07:12 UTC, mclasmeier commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{ include "srox.warn" (list $ "collector.slimMode is set to true, but it is deprecated and will be ignored.") }}
:+1:

2025-02-03 07:19 UTC, mclasmeier commented on roxctl/sensor/generate/generate.go
> +	autobool.NewFlag(c.PersistentFlags(), &generateCmd.slimCollectorP, slimCollector, "Use slim collector in deployment bundle. This option is ignored by Centrals newer than 4.6.")
nit: `4.6.1` would also be a newer than `4.6`. Maybe rephrase it something like `beginning with 4.7 ...`?

2025-02-03 09:08 UTC, Stringy commented on operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
> +                        description: Deprecated field.
Yes, I think it is deprecated now. This setting is specific to Collector, and we will only publish one image flavor now (regular)

2025-02-03 09:09 UTC, Stringy commented on roxctl/sensor/generate/generate.go
> +	autobool.NewFlag(c.PersistentFlags(), &generateCmd.slimCollectorP, slimCollector, "Use slim collector in deployment bundle. This option is ignored by Centrals newer than 4.6.")
Very good point, I'll adjust it.

2025-02-03 09:22 UTC, Stringy commented on central/clusters/deployer_test.go
>  			// These tests are failing right now but should succeed after RS-479 has been implemented
Done :smile:

2025-02-03 09:23 UTC, Stringy commented on image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
> +  {{ include "srox.warn" (list $ "collector.slimMode is set to true, but it is deprecated and will be ignored.") }}
Good point, done.

2025-02-03 09:37 UTC, Stringy commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> -@test "roxctl sensor generate: no overrides with collector full" {
Good point, I'll add a test here, but I think all we can do is check for success and lack of -slim suffix since these tests run against the same version of Central. 

Do we have other roxctl tests for version mismatches elsewhere?

2025-02-03 10:46 UTC, mclasmeier approved these changes
Thank you!
Just few minor nits/questions from my side.
Didn't review the UI changes.
After resolving the remaining open issues, I guess this can 🚢 .

2025-02-03 11:19 UTC, vikin91 commented on operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
> +                        description: Deprecated field.
Oh, I see, Indeed we are here in Collector context. 

This is a bit confusing, as we have 3 flavors: development, open-source, and RHACS. Here this field acts more as slim/non-slim selector. I think, we don't wand to deprecate the first, while we do want to get rid of the second. Is this correct?

2025-02-03 11:27 UTC, vikin91 commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> -@test "roxctl sensor generate: no overrides with collector full" {
I am not sure - maybe there are some used in e2e test where we use roxctl to deploy stuff? I don't think their goal is to test version mismatches though.

Even in bats, we may not have them at the moment. The path `/bats-tests/cluster` means that we need a running Central to execute those, but I don't remember adding bats tests for roxctl with different versions of Central (that is what I remember from 2022 when we worked on the flavors feature).

Adding a test that would deploy central in older version and run a bats suite may be an overkill for this PR, so I am fine to tackle this in a followup. But maybe we could add a test in `/bats-tests/local` to check that providing the slim option does not trigger any error similar to `unknown parameter --slim`?

2025-02-03 16:17 UTC, Stringy commented on operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
> +                        description: Deprecated field.
Yes exactly. We can't remove it completely for compatibility reasons, but I've made it so that new installations can't change it from regular, and upgrades are converted to regular

2025-02-03 17:54 UTC, vikin91 approved these changes
Approving, since the blocker-issue has been discussed and clarified.

2025-02-04 08:47 UTC, Stringy commented
/retest

2025-02-04 11:48 UTC, janisz commented on roxctl/sensor/generate/generate.go
> +
is this equal to (excluding the flag will be hidden)
```
	utils.Must(c.PersistentFlags().MarkDeprecated(slimCollector, warningSlimCollectorModeSet)
```

2025-02-04 11:48 UTC, janisz approved these changes

2025-02-04 13:10 UTC, Stringy commented on roxctl/sensor/generate/generate.go
> +
Done

2025-02-05 09:45 UTC, Stringy commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> -@test "roxctl sensor generate: no overrides with collector full" {
I've been thinking about this local test and I think if I add an `assert_line ...` for the deprecation warning to the new test here, then we can cover this behaviour. 

I'm not sure it makes sense to test this command (sensor generate) without some cluster there, so perhaps this would be a good middle ground until we can look at adding a test against an older central. WDYT?

2025-02-05 10:29 UTC, vikin91 commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> -@test "roxctl sensor generate: no overrides with collector full" {
Yes, that is fine to use a local test and assert on a line.

2025-02-05 10:40 UTC, Stringy commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> -@test "roxctl sensor generate: no overrides with collector full" {
Done

2025-02-05 11:50 UTC, Stringy commented on tests/roxctl/bats-tests/cluster/sensor-generate-image-overrides.bats
> -@test "roxctl sensor generate: no overrides with collector full" {
Or, to be more precise, _now_ it's done :sweat_smile:

2025-02-05 13:45 UTC, Stringy commented on pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/collector-slimfull-image-overrides.test.yaml
Done

2025-02-05 19:29 UTC, Stringy commented
/retest

2025-02-05 19:30 UTC, Stringy commented
Based on approvals from all teams (UI approval provided by Mark in https://github.com/stackrox/stackrox/pull/13350#issuecomment-2596869771) and test failures being flakes (re-running now) I'll set the pr to auto-merge once conversations are resolved.

2025-02-06 10:45 UTC, merged