ROX-10823: Add tests for replaced resources.
stackrox/stackrox pull request #1565
Opened 2022-05-05 00:56 UTC by dhaus67

## Description

Add additional tests to cover datastores where deprecated resources are used, ensuring that access to both old resources as well as new, grouped resource allows access.

## Testing Performed
- CI

2022-05-05 09:16 UTC, janisz approved these changes

2022-05-09 10:31 UTC, rhybrillou requested changes
Adding tests is good.
Some of the added tests do not rely on the appropriate context.
It would be better if all pre-existing datastore test functions (TestAllowsXXX) were validating the access with both old and new resource. Coverage could be extended in some of the files.

2022-05-09 10:31 UTC, rhybrillou commented on central/imageintegration/datastore/datastore_impl_test.go
>  func (suite *ImageIntegrationDataStoreTestSuite) TestEnforcesAdd() {
Should there be tests with suite.hasWriteIntegrationsCtx for Add, Update and Remove ?

2022-05-09 10:31 UTC, rhybrillou commented on central/license/datastore/datastore_impl_test.go
> +	err = s.dataStore.UpsertLicenseKeys(s.hasWriteCtx, []*storage.StoredLicenseKey{})
`s.hasWriteAccessCtx` instead of `s.hasWriteCtx`
Also applies to `TestAllowsDelete`

Should there be a change in `TestAllowsList` as well ?

2022-05-09 10:31 UTC, rhybrillou commented on central/notifier/datastore/datastsore_test.go
> +	err = s.dataStore.RemoveNotifier(s.hasWriteCtx, "notifier")
`s.hasWriteIntegrationsCtx` ?

2022-05-09 10:31 UTC, rhybrillou commented on central/serviceidentities/datastore/datastore_impl_test.go
>  func (s *serviceIdentityDataStoreTestSuite) TestAllowsAdd() {
Should `TestAllowsGet` also validate access with the new resource ?

2022-05-10 08:31 UTC, janisz approved these changes

2022-05-10 09:58 UTC, rhybrillou approved these changes

2022-05-10 11:43 UTC, merged