ROX-10864 mitre vector
stackrox/stackrox pull request #1616
Opened 2022-05-09 08:44 UTC by fredrb

## Description

Adds MITRE vectors to NetworkPolicy default policy

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [stackrox/openshift-docs](https://github.com/stackrox/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

- CI

2022-05-09 09:26 UTC, msugakov commented
Do you mind to link the Slack thread with discussion of vectors, etc?

2022-05-09 09:28 UTC, msugakov commented
Also, this should go in 3.70 release so that we don't need to create migration afterwards, right?
In this case, please tag it with the current milestone so that the release engineer cherry-picks it onto the release branch.

2022-05-09 09:29 UTC, msugakov commented
Finally, for "Testing Performed" section, you can spin up a copy in the cluster and check that MITRE things show up (in case UI shows them) for the policy.

2022-05-09 13:05 UTC, Maddosaurus approved these changes
Over all, I'd say it would be awesome to get someone from PM to verify we picked the correct vectors, but this is looking great as far as I can tell 🎉

2022-05-09 13:05 UTC, Maddosaurus commented on pkg/defaults/policies/files/deployment_has_ingress_network_policy.json
> +        "T1610"
Nitpick: Agree on T1610, but should we maybe sort this in Execution (T0002) instead of Defense Evasion (T0005)?

2022-05-09 13:05 UTC, Maddosaurus commented on pkg/defaults/policies/files/deployment_has_ingress_network_policy.json
> +        "T1046"
Yes - should we add T1049 as well?

2022-05-09 15:59 UTC, md2119 requested changes
I don't think MITRE applies to system policy that alerts on absence of ingress policy. The absence of an ingress policy does not in any way indicate an exploit.

2022-05-09 15:59 UTC, md2119 commented on pkg/defaults/policies/files/deployment_has_ingress_network_policy.json
> +        "T1498",
How does not having ingress policy map to DoS?

2022-05-09 15:59 UTC, md2119 commented on pkg/defaults/policies/files/deployment_has_ingress_network_policy.json
> +      "tactic": "TA0001",
How does not having ingress system policy indicate that an adversary is trying to gain access?

2022-05-09 15:59 UTC, md2119 commented on pkg/defaults/policies/files/deployment_has_ingress_network_policy.json
> +      "tactic": "TA0005",
How does not having ingress policy indicate that an adversary is trying to evade defenses?

2022-05-09 15:59 UTC, md2119 commented on pkg/defaults/policies/files/deployment_has_ingress_network_policy.json
> +        "T1610"
Not having ingress policy does not indicate that an adversary is deploying container? For example, a system policy to detect the creates of pods would be mapped this technique.

2022-05-10 09:10 UTC, fredrb commented
> I don't think MITRE applies to system policy that alerts on absence of ingress policy. The absence of an ingress policy does not in any way indicate an exploit.

@md2119 not adding vectors at all to this policy makes this task a no-op. We can simply close this PR and be done with it.

2022-05-10 09:49 UTC, Maddosaurus commented
@md2119  @fredrb 
+1 from my side for closing this PR for now as a no-op. We can always ship an update / migration should we decide to add vectors.

2022-05-10 13:50 UTC, closed without merging