ROX-10733: Add SAC integration tests for Pod Datastore.
stackrox/stackrox pull request #1636
Opened 2022-05-10 02:41 UTC by dhaus67

## Description

Add SAC integration tests for pod datastore.

Additionally, reduce code duplication and create generic `SACSearchTestCase` that can be applied when 27 scoped resources are used within the test, 9 per cluster, 3 per namespace in each cluster. This way we have the same generic test cases over multiple datastores, and potentially can still add custom ones, if desired. 

## Testing Performed
- see CI

2022-05-10 08:47 UTC, janisz commented
`gke-postgres-api-e2e-tests` are failing is this related to this PR?

2022-05-10 10:33 UTC, rhybrillou requested changes
Good job.
A few small details in the search test case parameters to iron out and it will be good to merge.

2022-05-10 10:33 UTC, rhybrillou commented on pkg/sac/testutils/search_test_cases.go
> +			ScopeKey: UnrestrictedReadCtx,
UnrestrictedReadWriteCtx ? (same applies to GenericUnrestrictedRawSACSearchTestCases)

2022-05-10 13:34 UTC, dhaus67 commented
@janisz Hm, `SACV2Test and ProcessBaselinesTest` seem to be flakes with timeout issues. The search one I'm not entirely sure why they would be connected, as they are searching for images / deployments 😞 Let me re-run the tests and observe whether the same issue occur once more.

2022-05-11 06:47 UTC, rhybrillou approved these changes

2022-05-11 08:42 UTC, janisz approved these changes

2022-05-11 11:53 UTC, merged