ROX-10993: Respect replaced resources within allow fixed scope checker.
stackrox/stackrox pull request #1794
Opened 2022-05-23 01:10 UTC by dhaus67

## Description

Continuation of a series of PRs to adapt `ScopeCheckerCore` implementations to respect replacing resources so that we can seamlessly deprecate resources now and in the future. For more general context, you can see the description of
#1756 .

This PR targets the `AllowedFixedScopes` implementation, which is usually used throughout our codebase like this:
```go
ctx := sac.WithGlobalAccessScopeChecker(context.Background(),
		sac.AllowFixedScopes(
			sac.AccessModeScopeKeys(storage.Access_READ_ACCESS),
			sac.ResourceScopeKeys(resources.APIToken)))
``` 

We expect the returned context `ctx` to have access to `resources.APIToken` as well as the replacing resource, `resources.Integration`. This has been achieved within this PR by:
- Adopting the interface `ResourceHandle` to include `GetReplacingResource`.
- Within `ResourceScopeKeys`, ensure we resolve replacing resources and conditionally add their scope keys as well.
- Adopt the `EffectiveAccessScope`, specifically the `getResourceEffectiveAccessScope` to conditionally verify replacing resources.

## Testing Performed
- Unit tests (see CI).
- Additionally running more QA tests (i.e. postgres) to ensure we don't have unexpected issues.

2022-05-24 14:14 UTC, janisz approved these changes

2022-05-24 15:49 UTC, rukletsov approved these changes
Looks good overall, thanks!

2022-05-24 15:49 UTC, rukletsov commented on pkg/sac/allow_fixed_scopes_checker_core.go
> +		_, resourceAllowed = c.topLevelKeys()[ResourceScopeKey(*resource.Resource.GetReplacingResource())]
Please don't do variable shadowing, instead say `replacingResourceAllowed`.

2022-05-25 01:14 UTC, dhaus67 commented on pkg/sac/scope_key.go
> +	// TODO(dhaus): Not sure this semantic change will bear issues.
Added the additional comment. I've checked throughout the code base, `ResourceScopeKeys` is at the moment only used in combination with `AllowFixedScopes`.

2022-05-25 06:56 UTC, rukletsov requested changes

2022-05-25 06:56 UTC, rukletsov commented on pkg/sac/scope_key.go
>  	keys := make([]ScopeKey, len(resources))
This creates a slice of length `n`, what you need is capacity `n` because you only append. So `keys := make([]ScopeKey, 0, len(resources))`

2022-05-25 06:56 UTC, rukletsov commented on pkg/sac/scope_key.go
> +// to the returned scope keys.
I'd also explicitly say that you think that the broadening is fine because of the contexts this function is used in.

2022-05-25 19:43 UTC, rukletsov approved these changes

2022-05-30 00:18 UTC, merged