Fix scope lookups in image and cluster Vulnerabilities sub-resolvers
stackrox/stackrox pull request #2715
Opened 2022-08-16 19:23 UTC by charmik-redhat

## Description

Some image and cluster vulnerability sub resolvers used to search the default ctx sent to the sub-resolver. The default ctx would not have the entity scoping added when vulnerabilities were queried from another entity. This PR updates the sub-resolvers in image and cluster vulnerability sub-resolvers to use the parent ctx to lookup scopes.

## Checklist
- [ ] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

Manual testing 
- Check if `fixedByVersion`, `isFixable` and `discoveredAtImage` in ImageVulnerability graphQL work as expected when `imageVulnerabilities` are queries from other entities.
- Check if `fixedByVersion` and `isFixable` in ClusterVulnerability graphQl work as expected.

2022-08-16 19:46 UTC, keyallis approved these changes
Good catch on these, they were probably changes I made when migrating old code over

2022-08-16 20:12 UTC, md2119 requested changes
Although conjunction query are built, make sure datastores are getting the correct context to reduce the confusion.

2022-08-16 20:12 UTC, md2119 commented on central/graphql/resolvers/cluster_vulnerabilities.go
>  func (resolver *clusterCVEResolver) FixedByVersion(ctx context.Context) (string, error) {
nit: `_ context.Context`

2022-08-16 20:12 UTC, md2119 commented on central/graphql/resolvers/cluster_vulnerabilities.go
> +	scope, hasScope := scoped.GetScope(resolver.ctx)
pass the `resolver.ctx` to the datastore

2022-08-16 20:12 UTC, md2119 commented on central/graphql/resolvers/cluster_vulnerabilities.go
> +	if scope, ok := scoped.GetScope(resolver.ctx); !ok || scope.Level != v1.SearchCategory_CLUSTER_VULNERABILITIES {
pass the `resolver.ctx` to the datastore

2022-08-17 21:22 UTC, md2119 approved these changes

2022-08-18 20:55 UTC, merged