Node Vulnerabilities graphQL go tests
stackrox/stackrox pull request #2815
Opened 2022-08-24 17:29 UTC by charmik-redhat

## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

2022-08-25 16:15 UTC, charmik-redhat commented
/test all

2022-08-26 18:42 UTC, md2119 approved these changes

2022-08-26 18:43 UTC, md2119 commented on central/graphql/resolvers/node_vulnerabilities_test.go
> +	nodeComponentCVEEdgePostgres.Destroy(s.ctx, s.db)
Do this before closing the gormDB

2022-08-26 19:07 UTC, md2119 commented on central/graphql/resolvers/node_vulnerabilities_test.go
> +		err = nodeStore.Upsert(s.ctx, node)
store must not be accessed directly. Most of our business logic lies in datastores. Call upsert on datastore.

2022-08-26 19:08 UTC, md2119 commented on central/graphql/resolvers/node_vulnerabilities_test.go
> +	// TODO CVSS not populated in node_cves table. Figure out how to test this
Because the test nodes are upserted directly into stores and not via datastores.

2022-08-26 19:10 UTC, md2119 commented on central/graphql/resolvers/node_vulnerabilities_test.go
> +		err = nodeStore.Upsert(s.ctx, node)
Similarly for image test.

2022-08-29 17:19 UTC, keyallis requested changes

2022-08-29 17:19 UTC, keyallis commented on central/graphql/resolvers/node_vulnerabilities_test.go
> +func testNodes() []*storage.Node {
Could you please move this function to the `test_utils.go` file, this could be reused in future tests on the node endpoint

2022-08-29 17:19 UTC, keyallis commented on central/graphql/resolvers/image_vulnerabilities_test.go
>  	scopedCtx := scoped.Context(ctx, scoped.Scope{
Please get rid of scopedCtx since it is no longer being used

2022-08-29 17:21 UTC, keyallis commented on central/graphql/resolvers/node_vulnerabilities_test.go
> +func (s *GraphQLNodeVulnerabilityTestSuite) TestTopNodeVulnerability() {
We should test that top vuln changes when scoped

2022-08-29 17:40 UTC, charmik-redhat commented on central/graphql/resolvers/image_vulnerabilities_test.go
>  	scopedCtx := scoped.Context(ctx, scoped.Scope{
scopedCtx is needed to fetch the ImageVulnerabilityResolver that is component scoped by calling `getImageVulnerabilityResolver`.

2022-08-29 17:43 UTC, charmik-redhat commented on central/graphql/resolvers/node_vulnerabilities_test.go
> +func (s *GraphQLNodeVulnerabilityTestSuite) TestTopNodeVulnerability() {
Yeah, testing it when it is node scoped in this test. I will add the test for when it is component scoped when adding node components tests.

2022-08-29 17:45 UTC, charmik-redhat commented on central/graphql/resolvers/node_vulnerabilities_test.go
> +func testNodes() []*storage.Node {
Yeah that's right. Moved the function.

2022-08-29 21:24 UTC, charmik-redhat commented
/retest-required

2022-08-29 22:17 UTC, merged