WIP:[FE][PERFORMANCE] Optimize list image graphQL query
stackrox/stackrox pull request #2941
Opened 2022-09-01 19:42 UTC by md2119

## Description

The nested image `scan` graphQL query pulls are components and vulns. Therefore, use the top-level `operatingSystem`, `scanTime` when components and vulns are not required.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

2022-09-07 23:48 UTC, md2119 commented
/retest-required

2022-09-08 21:24 UTC, md2119 commented on ui/apps/platform/src/Components/CVEStackedPill/CVEStackedPill.js
> +            {!hasScan && <span>{entityName} not scanned</span>}
@vjwilson, need your help to figure out why this expression evaluates falsy.

2022-09-08 22:04 UTC, vjwilson requested changes
Made a suggestion which should be the last piece of the puzzle.

2022-09-09 13:50 UTC, vjwilson approved these changes
FE looks good

2022-09-12 16:42 UTC, md2119 commented
/test ui-unit-tests

2022-09-12 23:49 UTC, merged