Generate JUnit report for sensor tests
stackrox/stackrox pull request #3080
Opened 2022-09-14 10:25 UTC by janisz

## Description

Sensors tests are stored in different files then other go tests and junit report is not generated for them.
This PR stores all sensors tests output into a single file (the same as other tests) and generate junit report from it saving it in prow so it will be visible with lenses.

## Testing Performed
CI

2022-09-14 10:25 UTC, janisz commented
Current dependencies on/for this PR:
* master
  * **PR #3080** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3080" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3080?utm_source=stack-comment).

2022-09-14 13:44 UTC, janisz commented
/retest

2022-09-14 16:19 UTC, lvalerom approved these changes
LGTM. I added a comment regarding the log files for `sensor-integration-test`.

2022-09-14 16:19 UTC, lvalerom commented on Makefile
> +		| tee $(GO_TEST_OUTPUT_PATH); \
I'm not sure if there was a reason to have the logs of each test in separate files. I'm ok with having them in one file though.

2022-09-14 16:38 UTC, lvalerom requested changes
I think `sensor-integration-test` should stay they way they were, otherwise we are overwriting the previous logs.

2022-09-15 10:01 UTC, janisz commented
/retest

2022-09-15 12:29 UTC, janisz commented
/retest

2022-09-15 14:09 UTC, lvalerom requested changes
The `sensor-integration-tests` won't work like this. We rely on the test context to close some things for us, that's why we needed the `for` loop to execute the tests individually. If they run all at the same time, they won't pass. This behavior is something that we are planning to change at some point, but not right now.

2022-09-15 14:09 UTC, lvalerom commented on Makefile
> +		$(shell git git ls-files -- 'sensor/tests/*_test.go'  | sed -e 's@^@./@g' | xargs -n 1 dirname | sort | uniq | xargs go list) \
You have `git` twice in this line.

2022-09-16 09:07 UTC, janisz commented
/retest

2022-09-16 13:09 UTC, janisz commented
/retest

2022-09-16 14:37 UTC, lvalerom approved these changes
LGTM

2022-09-19 09:59 UTC, merged