go 1.18 follow up
stackrox/stackrox pull request #3196
Opened 2022-09-26 13:27 UTC by 0x656b694d

## Description

Bump go version for static check, update generated files.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] ~Unit test and regression tests added~
- [ ] ~Evaluated and added CHANGELOG entry if required~
- [ ] ~Determined and documented upgrade steps~
- [ ] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

2022-09-26 15:12 UTC, 0x656b694d commented
/retest-required

2022-09-26 16:46 UTC, janisz commented on roxctl/helm/output/output_test.go
> +			chartName:    common.ChartCentralServices,
🤔  
```
roxctl/helm/output/output_test.go:111: File is not `gofmt`-ed with `-s` (gofmt)
			chartName:    common.ChartCentralServices,
```

2022-09-27 11:37 UTC, rukletsov requested changes
I'd stick to making only necessary changes. It seems to be accepted by our CI: https://github.com/stackrox/stackrox/pull/3207

2022-09-28 09:18 UTC, janisz commented
> I'd stick to making only necessary changes. It seems to be accepted by our CI

@rukletsov I think it's fine to change formatting. If we do not do this then this changes will randomly appear when someone runs gofmt on file and commit it.

2022-09-28 10:00 UTC, rukletsov approved these changes

2022-09-28 10:03 UTC, merged