ROX-13187 + ROX-13188: Adding the YAML display and export button to the namespace side panel
stackrox/stackrox pull request #3479
Opened 2022-10-18 23:51 UTC by sachaudh

## Description

This PR adds the YAML and export button to the namespace side panel. This is an iterative addition to the namespace side panel. You can view the related sub-tasks for the namespace side panel here: https://issues.redhat.com/browse/ROX-13186

## Checklist
- [x] Investigated and inspected CI test results
- [ ] ~Unit test and regression tests added~
- [ ] ~Evaluated and added CHANGELOG entry if required~
- [ ] ~Determined and documented upgrade steps~
- [ ] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Screenshots

<img width="1552" alt="Screen Shot 2022-10-18 at 4 47 50 PM" src="https://user-images.githubusercontent.com/4805485/196565899-ac71b343-bd4b-46a6-bcdd-c078882a3bb7.png">

2022-10-19 16:47 UTC, sachaudh commented on ui/apps/platform/package.json
> +        "monaco-editor": "^0.34.1",
Had some issues with adding the @patternfly/react-code-editor library. I had to install this one as well to fix the issues

2022-10-20 16:29 UTC, vjwilson requested changes
Remove hard-coded `isDarkTheme` prop for now.

If possible, remove explicit inclusion of base `monaco-editor` package, if `react-monaco-editor` inclusion will suffice.

2022-10-20 16:32 UTC, sachaudh commented on ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceNetworkPolicies.tsx
> +                        isDarkTheme
I personally don't mind either method, but I think @alanonthegit wanted the editor to be in dark mode regardless of the current theme 

![Screen Shot 2022-10-20 at 9 31 45 AM](https://user-images.githubusercontent.com/4805485/197006545-61a6cf4c-629d-4105-8f79-3d08b1a38025.png)

2022-10-20 16:33 UTC, sachaudh commented on ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceNetworkPolicies.tsx
> +                        isDarkTheme
If it's something the OpenShift UI does, might be better to keep it consistent

2022-10-20 17:46 UTC, sachaudh commented on ui/apps/platform/package.json
> +        "monaco-editor": "^0.34.1",
Yea, otherwise this happens

![Uploading Screen Shot 2022-10-20 at 10.45.44 AM.png…]()

2022-10-21 13:51 UTC, vjwilson commented on ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceNetworkPolicies.tsx
> +                        isDarkTheme
I think forcing it dark, regardless of the theme, is not good for accessibility. (For example, even though I had Lasik in the recent past, I cannot easily read the dark theme editor.)

Nicole with the PF team suggested that we take advantage of the [custom control feature of the PF editor component](https://www.patternfly.org/v4/components/code-editor/#with-custom-control) to just allow users to toggle it. (They could even make it light while the rest of the page is dark theme--I would definitely do that while doing demos, just for the shock value. 😉 )

We could even default it to dark, if you like.

```suggestion
                        // with the appropriate setState/clickHandler to track this
                        isDarkTheme={isEditorDark}
                        customControls={customControl}
```

2022-10-21 16:28 UTC, alanonthegit commented on ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceNetworkPolicies.tsx
> +                        isDarkTheme
I'm good with default dark, and having the option for user theme override 👍

2022-10-26 19:17 UTC, sachaudh commented on ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceNetworkPolicies.tsx
> +                        isDarkTheme
<img width="1440" alt="Screen Shot 2022-10-26 at 12 16 16 PM" src="https://user-images.githubusercontent.com/4805485/198116742-0d850602-0e8e-42a1-a13e-9037a1e7cc84.png">
<img width="1440" alt="Screen Shot 2022-10-26 at 12 16 32 PM" src="https://user-images.githubusercontent.com/4805485/198116748-a0c708c0-9ec3-4da2-b543-9b6b9fd60c75.png">

2022-10-27 05:44 UTC, sachaudh commented on ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceNetworkPolicies.tsx
> +                        isDarkTheme
@alanonthegit syntax highlighting wasn't working for me. I asked the question in the PF slack channel. For now, I think we should move things along (cc: @vjwilson @alwayshooin )

2022-10-27 15:30 UTC, vjwilson approved these changes

2022-10-27 17:38 UTC, merged