fix: shellcheck fixes for roxctl.sh
stackrox/stackrox pull request #3569
Opened 2022-10-26 07:11 UTC by kadern0

Signed-off-by: Pablo Caderno <kaderno@gmail.com>

## Description

Fix shellcheck warnings for roxctl.sh as per #3544

2022-10-26 16:33 UTC, janisz requested changes
Please remove `dev-tools/roxctl.sh` from https://github.com/stackrox/stackrox/blob/master/scripts/style/shellcheck_skip.txt#L16

2022-10-26 16:34 UTC, janisz commented
/ok-to-test

2022-10-27 12:55 UTC, janisz requested changes

2022-10-27 12:55 UTC, janisz commented on dev-tools/roxctl.sh
> +      kubectl get clusterversions.config.openshift.io version | grep -v "No resources found" > /dev/null
If we have a function we can check both conditions at once
```suggestion
      kubectl get clusterversions.config.openshift.io version | grep -v "No resources found" > /dev/null && kubectl get centrals.platform.stackrox.io -n stackrox | grep -v "No resources found" > /dev/null
```

2022-11-02 12:58 UTC, janisz commented on dev-tools/roxctl.sh
>    fi
```suggestion
```
`mycmd could be removed once you included it in `cmd`

2024-03-28 10:36 UTC, porridge commented
Closing this stale PR.
@kadern0 please reopen once you rebase and resolve conflicts.

2024-03-28 10:36 UTC, closed without merging