ROX-13466: Fix deletion of groups with empty properties
stackrox/stackrox pull request #3756
Opened 2022-11-09 13:54 UTC by dhaus67

## Description

For additional context, see [ROX-13446](https://issues.redhat.com/browse/ROX-13446) as well.

During startup and the initialization of the group datastore, we attempt to delete groups with empty properties.

This has been there historically for quite some time ([the initial PR that introduced this](https://github.com/stackrox/rox/pull/1659) + [the associated ticket ROX-1698](https://issues.redhat.com/browse/ROX-1698)).

Now, we added validation with the move from the tuple ID key for groups (using its propreties) to a single UUID.
This leads to an issue when trying to remove groups with empty properties during startup.
Since the properties will be empty, the validation which is done within the `Remove` call, will fail (since the validation is checking whether auth provider ID is set etc.).

Within this PR, a separate function has been introduced at the datastore layer that will:
- retrieve all groups with empty properties.
- delete those groups, skipping validation and other mutability trait verification.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
~~- [ ] Evaluated and added CHANGELOG entry if required~~
~~- [ ] Determined and documented upgrade steps~~
~~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into 
[rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

If any of these don't apply, please comment below.

## Testing Performed

- see unit tests added running within CI and passing.

2022-11-09 13:54 UTC, dhaus67 commented
Current dependencies on/for this PR:
* master
  * **PR #3756** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3756" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3756?utm_source=stack-comment).

2022-11-09 13:57 UTC, janisz approved these changes

2022-11-09 15:23 UTC, ivan-degtiarenko requested changes
From the initial look at it, I don't see why we can't change the direction here compared to the one chosen here https://issues.redhat.com/browse/ROX-1698 and make it a migration. That would allow us to avoid introducing and supporting `RemoveAllWithEmptyProperties` which doesn't have any other potential applications.

2022-11-11 15:54 UTC, ivan-degtiarenko approved these changes
As discussed offline, migration will potentially be done in a separate PR - this PR addresses only empty `authProviderId`, `key` and `value` cases. This PR doesn't address the `nil` props case.

LGTM 🚢

2022-11-11 15:59 UTC, dhaus67 commented
/retest

2022-11-11 16:53 UTC, merged