ROX-13479: Add simulate network policies tab
stackrox/stackrox pull request #4069
Opened 2022-12-08 19:57 UTC by sachaudh

## Description

This PR is an iterative addition for the network policy simulation side panel. Things that were included:
1. A new type called `Simulation` was created to show whether the simulation mode is on and what type of simulation it is (ie. `network policy` or `baseline`)
2. The simulation state will be kept in the URL like this: `.../network-graph/?s[Simulation]=network policy` or `.../network-graph/deployment/:id?s[Simulation]=baseline`
3. Changes were made in `NetworkGraphPage` and `NetworkGraph` to decide when to show the network policy simulation side panel 
4. Changes were made in `NetworkGraph`, specifically in the functions where we select a node or close the side panel, to remove the simulation state from the search query. The method I used could be improved, and we can consider maybe using a state machine or some way to synchronize the state better

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

2022-12-09 16:08 UTC, vjwilson requested changes
Markup looks good, but let's separate the query used for this display option from the actual "search" part of the query string.

2022-12-09 16:08 UTC, vjwilson commented on ui/apps/platform/src/Containers/NetworkGraph/simulation/SimulateNetworkPolicyButton.tsx
> +        history.push(networkBasePathPF);
We shouldn't overwrite the URL params; we don't need this line.

```suggestion

```

2022-12-10 00:39 UTC, sachaudh commented on ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
> +}
Ok it should now be changed to `https://localhost:3000/main/network-graph?s[Cluster]=remote&s[Namespace][0]=stackrox&simulation=networkPolicy`

2022-12-10 00:40 UTC, sachaudh commented on ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
> +}
I'm using the `useURLParameter` hook that I see Dave has been using in his Collection-related components

2022-12-13 21:22 UTC, vjwilson approved these changes

2022-12-13 22:42 UTC, merged