ROX-9094: Create tasks for failing tests
stackrox/stackrox pull request #4103
Opened 2022-12-12 16:54 UTC by janisz

2022-12-13 14:03 UTC, janisz commented
/retest

2022-12-13 18:44 UTC, gavin-stackrox commented on scripts/ci/lib.sh
> +        ./junit2jira -junit-reports-dir "$from"
Given that it is a prototype have it silently fail and not disrupt following functionality:
```suggestion
{
        info "Creating JIRA task for failures found in $from"
        wget -q https://github.com/janisz/junit2jira/releases/download/v0.0.1/junit2jira && \
        chmod +x junit2jira && \
        ./junit2jira -junit-reports-dir "$from"
} || true
```

2022-12-13 18:45 UTC, gavin-stackrox requested changes

2022-12-13 18:45 UTC, gavin-stackrox commented on scripts/ci/lib.sh
> +        wget -q https://github.com/janisz/junit2jira/releases/download/v0.0.1/junit2jira && \
```suggestion
        wget -q https://github.com/stackrox/junit2jira/releases/download/v0.0.1/junit2jira && \
```

2022-12-13 20:22 UTC, janisz commented on scripts/ci/lib.sh
> +        wget -q https://github.com/janisz/junit2jira/releases/download/v0.0.1/junit2jira && \
https://github.com/stackrox/junit2jira/releases/tag/v0.0.1

2022-12-14 11:23 UTC, porridge approved these changes
I'd feel much safer if this ran *after* the `cp` in case `junit2jira` blows through some deadline or memory limit.

2022-12-14 14:15 UTC, janisz commented on scripts/ci/lib.sh
> +        wget -q https://github.com/stackrox/junit2jira/releases/download/v0.0.1/junit2jira && \
For some reason `curl` could not download the file but `wget` can.
wget has `--tries` option that by default is set to 20.

2022-12-14 16:04 UTC, janisz commented
@gavin-stackrox PTAL

2022-12-15 09:09 UTC, porridge commented on scripts/ci/lib.sh
> +        wget -q https://github.com/stackrox/junit2jira/releases/download/v0.0.1/junit2jira && \
Interesting, works for me.
```
$ curl -o j2j -L https://github.com/stackrox/junit2jira/releases/download/v0.0.1/junit2jira
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2317k  100 2317k    0     0   612k      0  0:00:03  0:00:03 --:--:--  869k
$ file j2j
j2j: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header
```

But I'm not insisting, 20 retries SGMT

2022-12-15 09:48 UTC, janisz commented on scripts/ci/lib.sh
> +        wget -q https://github.com/stackrox/junit2jira/releases/download/v0.0.1/junit2jira && \
My bad, I used `-l` instead of `-L`

2022-12-15 16:58 UTC, gavin-stackrox approved these changes
LGTM!

2022-12-15 16:58 UTC, merged