ROX-10003: Adjust ...Id naming to ...ID for style compliance
stackrox/stackrox pull request #4210
Opened 2022-12-20 12:47 UTC by rhybrillou

## Description

Pieces of the postgres generated store code do not comply with style requirements.
The goal of this change is to ensure generated postgres store code match style requirements.

## Checklist
- [ ] Investigated and inspected CI test results
~~- [ ] Unit test and regression tests added~~
~~- [ ] Evaluated and added CHANGELOG entry if required~~
~~- [ ] Determined and documented upgrade steps~~
~~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

If any of these don't apply, please comment below.

## Testing Performed

CI is sufficient.

2022-12-20 12:47 UTC, rhybrillou commented
/test all

2022-12-20 13:44 UTC, rhybrillou commented
/test all

2022-12-21 16:32 UTC, rhybrillou commented
/test all

2023-01-02 13:28 UTC, janisz approved these changes

2023-01-02 13:28 UTC, janisz reviewed
Should we also change stores used in migration?

2023-01-03 10:26 UTC, dashrews78 commented on tools/generate-helpers/pg-table-bindings/store.go.tpl
> +//// Used for testing
nit:  I think the testing functions should remain at the bottom though that may just be my personal preference.

2023-01-03 10:27 UTC, dashrews78 approved these changes
Just one nit to consider or not consider.

2023-01-03 22:29 UTC, md2119 requested changes

2023-01-03 22:29 UTC, md2119 commented on central/activecomponent/datastore/internal/store/postgres/store.go
>  func (s *storeImpl) copyFrom(ctx context.Context, objs ...*storage.ActiveComponent) error {
newline

2023-01-03 22:36 UTC, md2119 commented on central/activecomponent/datastore/internal/store/postgres/store.go
> +			err = errors.Wrapf(err, "unable to delete the records.  Successfully deleted %d out of %d", numRecordsToDelete-len(identifiers), numRecordsToDelete)
This message does not indicate the resource kind. It becomes a problem if this delete is just a steps belonging to a workflow. For example, deleting service account, namespaces, etc. when a cluster is deleted.

This message could be polished to indicate the resource kind like `unable to delete the %s records...", baseTable, ...`

2023-01-05 21:28 UTC, rhybrillou commented
/retest

2023-01-09 08:29 UTC, rhybrillou commented on central/activecomponent/datastore/internal/store/postgres/index.go
> -func (b *indexerImpl) DeleteActiveComponent(id string) error {
Reverted the change on the index template.

2023-01-10 17:08 UTC, md2119 approved these changes

2023-01-12 00:18 UTC, c-du approved these changes

2023-01-13 09:33 UTC, merged