Telemetry: remove unused Telemeter.Start() method
stackrox/stackrox pull request #4236
Opened 2022-12-21 17:06 UTC by 0x656b694d

## Description

Telemeter.Start() was added to complete the symmetry with Stop(), but now
is being removed as there's no plan to use it.

2022-12-21 17:07 UTC, 0x656b694d commented
Current dependencies on/for this PR:
* master
  * **PR #4214** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4214" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4236** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4236" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/4236?utm_source=stack-comment).

2022-12-23 10:01 UTC, rukletsov requested changes

2022-12-23 10:01 UTC, rukletsov commented on pkg/telemetry/phonehome/telemeter.go
> -	Start()
And one more in `segmentTelemeter`.

2022-12-23 13:24 UTC, rukletsov approved these changes

2022-12-23 14:10 UTC, merged