Set ownership of CI dirs to CI team
stackrox/stackrox pull request #4411
Opened 2023-01-16 12:57 UTC by janisz

## Description

To keep consistent CI configs we should automatically add owners to review.

2023-01-16 13:19 UTC, tommartensen commented
I like the idea. Could we add `scripts/ci/**` to the list?
What do you think about renaming the team to something like `upstream-ci`? (I am also happy to join the team :) )

2023-01-16 13:22 UTC, janisz commented
> I like the idea. Could we add scripts/ci/** to the list?

Fixed

> What do you think about renaming the team to something like upstream-ci? (I am also happy to join the team :) )

To do this we need @gavin-stackrox help

2023-01-16 14:27 UTC, janisz commented
/retest

2023-01-16 23:33 UTC, gavin-stackrox commented
I've created @stackrox/ci https://github.com/orgs/stackrox/teams/ci (see if you can self add, if not I will add anyone that wants to join).

2023-01-16 23:34 UTC, gavin-stackrox approved these changes

2023-01-17 07:09 UTC, tommartensen commented
> see if you can self add, if not I will add anyone that wants to join

Requested to join team.

2023-01-17 07:13 UTC, tommartensen requested changes

2023-01-17 07:13 UTC, tommartensen commented on .github/CODEOWNERS
> +.github/**/* @stackrox/circleci
Should be the new `@stackrox/ci` team now (same for the other two directories) 🙂

2023-01-17 10:56 UTC, janisz commented
```
Unknown owner on line 32: make sure the team @stackrox/ci exists and has write access to the repository
.github/**/* @stackrox/ci
Unknown owner on line 33: make sure the team @stackrox/ci exists and has write access to the repository
.openshift-ci/**/* @stackrox/ci
Unknown owner on line 34: make sure the team @stackrox/ci exists and has write access to the repository
scripts/ci/** @stackrox/ci
```
@gavin-stackrox could add team to repo?

2023-01-17 11:06 UTC, tommartensen approved these changes
LGTM!

2023-01-19 09:30 UTC, merged