Merge API Reference and Help Center integration tests
stackrox/stackrox pull request #4418
Opened 2023-01-16 20:52 UTC by pedrottimark

## Description

Prerequisite to replace backend redirect for /docs/product with frontend link to OpenShift docs page.

### Changed files

1. Delete cypress/constants/Docs.js

2. Rename cypress/integration/apiReference.test.js as main/HelpMenu.test.js [too many changes to compare side-by-side]
    * Add `describe` block for Help Center.
    * Add `describe` block for version number.

3. Delete cypress/integration/docs.test.js

4. Edit src/Containers/MainPage/Header/HelpMenu.tsx
    * Merge items into one `ApplicationLauncherGroup` element to prepare for conditional rendering of Help Center, separator, and version number.

### Residue

1. Move files from credentialExpiry folder into main folder.
2. Add tests for other banners.

## Checklist
- [x] Investigated and inspected CI test results
- [x] Edited integration tests

## Testing Performed

Ran tests individually with local deployment before and after editing.

Help menu has same appearance after merging two `ul` into one.
![Help_menu](https://user-images.githubusercontent.com/11862657/212763286-c32eb173-bea4-42eb-a8a7-d5d3788242f3.png)

2023-01-17 14:34 UTC, 0x656b694d requested changes

2023-01-17 14:34 UTC, 0x656b694d commented on ui/apps/platform/cypress/integration/main/help.test.js
> +            cy.get('button[aria-label="Help menu"').click();
```suggestion
            cy.get('button[aria-label="Help menu"]').click();
```

2023-01-17 14:43 UTC, pedrottimark commented on ui/apps/platform/cypress/integration/main/help.test.js
> +            cy.get('button[aria-label="Help menu"').click();
Good eyes!

2023-01-17 21:24 UTC, bradr5 approved these changes
Tests make sense to me 👍

2023-01-18 13:34 UTC, 0x656b694d approved these changes
LGTM

2023-01-18 15:33 UTC, merged