Track database backups and store database backup metadata
stackrox/stackrox pull request #4498
Opened 2023-01-20 18:03 UTC by md2119

## Description

Add infrastructure to track backups and persist backup metadata.

**Note:**
- The check to abort migration is not in this PR
- This is only forward-looking i.e. it is only enabled when running on postgres.
- If we decide to ship 3.74 with rocksDB default, I can go ahead and add rocksDB store and its rockdb-postgres migration.

## Checklist
- [ ] Investigated and inspected CI test results
- [X] Unit test and regression tests added
- ~Evaluated and added CHANGELOG entry if required~
- ~Determined and documented upgrade steps~
- ~Documented user facing changes~

If any of these don't apply, please comment below.

## Testing Performed
CI

2023-01-20 18:39 UTC, dashrews78 requested changes
I learned the hard way that we can't update the metadata service and its message.  It breaks sensors because they use jsonp to unmarshal in default mode which does not allow for unknown fields.  Most of that has been resolved BUT won't be delivered until 74 and won't make it to the sensors until the users chooses to upgrade them.  So sadly I think we need to put this info some other place.

Here is the ticket which references a slack thread for some additional info for you.
https://issues.redhat.com/browse/ROX-14188

2023-01-20 18:48 UTC, md2119 commented
> I learned the hard way that we can't update the metadata service and its message. It breaks sensors because they use jsonp to unmarshal in default mode which does not allow for unknown fields. Most of that has been resolved BUT won't be delivered until 74 and won't make it to the sensors until the users chooses to upgrade them. So sadly I think we need to put this info some other place.
> 
> Here is the ticket which references a slack thread for some additional info for you. https://issues.redhat.com/browse/ROX-14188

Thanks for the heads-up, @dashrews78 . However, I am not changing the existing metadata service but adding a new service to the metadata server. Would that still break?

2023-01-20 18:52 UTC, dashrews78 commented
> > I learned the hard way that we can't update the metadata service and its message. It breaks sensors because they use jsonp to unmarshal in default mode which does not allow for unknown fields. Most of that has been resolved BUT won't be delivered until 74 and won't make it to the sensors until the users chooses to upgrade them. So sadly I think we need to put this info some other place.
> > Here is the ticket which references a slack thread for some additional info for you. https://issues.redhat.com/browse/ROX-14188
> 
> Thanks for the heads-up, @dashrews78 . However, I am not changing the existing metadata service but adding a new service to the metadata server. Would that still break?

Yes that is fine.  That is what I had to do with the database status stuff in there.  Now that `google.protobuf.Timestamp backup_last_run_at = 5;` is out of the metadata message this is no longer a concern

2023-01-20 19:09 UTC, dashrews78 commented on central/globaldb/export/backup.go
> +	listen := func(err error) error {
nit:  Not really using `listen` for this routine so we could remove it or not.

2023-01-20 19:21 UTC, dashrews78 commented on central/metadata/service/service_impl.go
> +	return &v1.DatabaseBackupStatus{
I wonder if all this info should be for authenticated users only.  I can't think what insight we would risk providing a backup time or that it succeeded to an user that is anonymous but it feels like too much.

2023-01-20 19:58 UTC, md2119 commented on central/metadata/service/service_impl.go
> +	return &v1.DatabaseBackupStatus{
I am not sure if the info is exploitable. I was wondering if and when operator communicates with Central for this info, would it be anonymous? 

That said, open to redact the message if you strongly feel about it.

2023-01-20 20:02 UTC, dashrews78 commented on central/metadata/service/service_impl.go
> +	return &v1.DatabaseBackupStatus{
I do not feel strongly one way or the other.  Figured I should pose the question just in case it triggered a thought for someone.  And that is a good point about operator but of course I do not know the answer to that.

2023-01-20 20:03 UTC, dashrews78 approved these changes

2023-01-23 18:25 UTC, md2119 commented on central/metadata/service/service_impl.go
> +	return &v1.DatabaseBackupStatus{
defaulted to using admin sac

2023-01-23 23:03 UTC, merged