Update go version in go.mod
stackrox/stackrox pull request #4663
Opened 2023-02-01 18:01 UTC by janisz

## Description

Tools and linters requires Go 1.19 to work. Go 1.19 is also required by k8s dependencies. This PR bumps required go version in go mod to 1.19

See:
- https://github.com/kubernetes/api/commit/e281bde5048c6909a89c7d14f1b8fd0d80849938
- https://github.com/golangci/golangci-lint/pull/3037
  

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI

2023-02-01 18:02 UTC, janisz commented
Current dependencies on/for this PR:
* master
  * **PR #4648** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4648" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4658** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4658" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #4649** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4649" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #4663** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4663" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/4663?utm_source=stack-comment).

2023-02-01 18:03 UTC, connorgorman requested changes
What changes were made to require go 1.19?

2023-02-07 07:06 UTC, porridge commented
This PR does not seem to be ready for review. Please ping us when it is.

2023-02-08 10:15 UTC, janisz commented
@connorgorman Just first example https://github.com/stackrox/stackrox/pull/4772

2023-02-09 14:23 UTC, janisz commented
/retest

2023-02-14 16:04 UTC, 0x656b694d approved these changes
Go go go!

2023-02-15 20:37 UTC, md2119 approved these changes

2023-02-17 11:18 UTC, closed without merging

2023-02-17 11:19 UTC, janisz commented
Closing. We can bump required go version when it will be necessary