ROX-12848: Set Postgres flag to permanently enabled
stackrox/stackrox pull request #4690
Opened 2023-02-02 20:43 UTC by connorgorman

## Description

Sets the Postgres flag to always be the default value of the setting

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI

2023-02-03 18:45 UTC, gavin-stackrox commented
/test openshift-newest-qa-e2e-tests openshift-penultimate-qa-e2e-tests openshift-oldest-qa-e2e-tests

2023-02-03 19:12 UTC, gavin-stackrox commented
/test openshift-newest-qa-e2e-tests openshift-penultimate-qa-e2e-tests openshift-oldest-qa-e2e-tests

2023-02-06 10:39 UTC, SimonBaeumer requested changes

2023-02-06 11:12 UTC, dashrews78 commented on central/processlisteningonport/datastore/datastore_impl_test.go
> +	pgtest.SkipIfPostgresEnabled(t)
PLOP is Postgres only.  Shouldn't we only skip it if Postgres is disabled?

2023-02-06 11:15 UTC, janisz reviewed
I think this should be splitted into smaller PRs. 
- Fix go code and prepare it for this change
- fix shell and makefile
- everything else

2023-02-06 18:35 UTC, connorgorman commented on scripts/ci/jobs/gke_nongroovy_e2e_tests.py
> +# Postgres is on by default
Sure, this is because these tests expect Postgres to be off and these are covered by the go version of these tests

2023-02-08 23:17 UTC, connorgorman commented on scripts/ci/jobs/gke_upgrade_tests.py
> +exit(0)
I added a better comment

2023-02-08 23:17 UTC, connorgorman commented on tests/roxctl/bats-tests/local/expect/flavor-interactive.expect.tcl
> +# Enter central-db image to use (default: "registry.redhat.io/advanced-cluster-security/rhacs-central-db-rhel8:3.68.x-30-g516b4e7a6c-dirty"):
This is just a comment to illustrate the expect below cases

2023-02-09 09:08 UTC, SimonBaeumer approved these changes

2023-02-09 10:33 UTC, dashrews78 approved these changes

2023-02-10 06:48 UTC, merged

2023-02-10 07:16 UTC, porridge commented
The fact that all openshift-*qa-e2e-tests failed worries me. For example:
```
Requesting stop of task ':testBAT' as it has exceeded its configured timeout of 3h.
```

Are we sure these failures are not related to this change @connorgorman ?