ROX-14148: Prefactor Transformer abstraqction for declarative configuration.
stackrox/stackrox pull request #4697
Opened 2023-02-03 05:06 UTC by dhaus67

## Description

This PR is a prefactor for [ROX-14148](https://issues.redhat.com/browse/ROX-14148) and adds an abstraction for transforming a declarative configuration to its associated proto message(s).

The previously introduced `ConfigurationType` will be re-used to distinguish which transformer to use.

For now, the default transformer created and used within the declarative configuration manager will not have any transformer implementations associated with it, those will be added at in follow-up PRs in the context of [ROX-14148](https://issues.redhat.com/browse/ROX-14148).

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

- no testing requried.

2023-02-03 05:06 UTC, dhaus67 commented
Current dependencies on/for this PR:
* master
  * **PR #4696** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4696" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4697** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4697" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #4698** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/4698" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/4697?utm_source=stack-comment).

2023-02-03 11:27 UTC, ivan-degtiarenko requested changes

2023-02-03 11:27 UTC, ivan-degtiarenko commented on central/declarativeconfig/transform/transformer.go
> +	Transform(config declarativeconfig.Configuration) ([]proto.Message, error)
I suggest we modify this interface to something closer to
```
  Transform(config declarativeconfig.Configuration) (map[reflect.Type]proto.Message, error)
```
The difficulty with the current interface can come when we start to process auth provider + groups together. If we have a map where auth provider and groups are in separate buckets, we can insert auth provider first and then groups. If we have a list, we need to find auth provider within it by casting.

2023-02-03 11:27 UTC, ivan-degtiarenko commented on central/declarativeconfig/transform/transformer.go
> +type defaultTransformer struct {
nit: IMHO `default` does not tell us what is the meaning of this transformer. Perhaps `combined` or `universal`?

2023-02-03 11:27 UTC, ivan-degtiarenko commented on central/declarativeconfig/transform/transformer.go
> +		return nil, errox.NotFound.Newf("no transformation logic for declarative config type %s found", config.Type())
I'm not sure we should use `NotFound` here as it is generally reserved for **user-controlled** resources not being present. This seems more like `InvariantViolation` to me

2023-02-07 02:50 UTC, dhaus67 commented
/retest

2023-02-07 11:56 UTC, ivan-degtiarenko approved these changes
LGTM

2023-02-07 20:53 UTC, merged