Fix handling empty string matches
stackrox/stackrox pull request #5211
Opened 2023-03-13 10:04 UTC by erthalion

## Description

Trimming values and building new string query do not handle empty strings correctly.

The first one is missing out to extract it out of double quotes due to the length condition (an empty string is `""`, which is exactly the same lenght as 2 * `"`, where the `"` is EqualityPrefixSuffix). This leads to an empty string being represented as `\"\"` along the way, producing incorrect search results.

The second one assumes that an empty string is something incorrect, although it's totally fine to search for values equal empty string.

## Checklist
- [ ] Investigated and inspected CI test results
- [x] Unit test and regression tests added
- [x] Evaluated and added CHANGELOG entry if required
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

Local testing via running a unit-test with an empty string search query.

2023-03-14 22:25 UTC, md2119 requested changes
Add some unit tests that directly tests exported function `GetValueAndModifiersFromString`.
For example,
`test`
`"test"`
`""`
`"`
`"test`

2023-03-21 09:33 UTC, erthalion commented
@md2119 now the fix has more tests for modifiers.

2023-03-21 23:00 UTC, connorgorman approved these changes

2023-03-22 08:30 UTC, erthalion commented
/retest-required

2023-03-22 17:18 UTC, md2119 approved these changes
Thanks for the tests and for fixing the panic case from the first commit.

2023-03-23 09:22 UTC, merged