ROX-13758: restore old failure message to fix UI CI failures
stackrox/stackrox pull request #5407
Opened 2023-03-27 22:14 UTC by keyallis

## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

2023-03-27 22:16 UTC, keyallis commented
/test gke-ui-e2e-tests

2023-03-27 22:24 UTC, clickboo approved these changes
Would have loved the error message to be what it was changed from - since its more clear. Guess it can change after the UI test is fixed to expect it.

2023-03-27 22:49 UTC, theencee commented on central/resourcecollection/service/service_impl.go
> +		return nil, errors.Wrap(errox.ReferencedByAnotherObject, "Failed to delete collection")
why not update the test? https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/cypress/integration/vulnmanagement/reporting/reportingForm.test.js#L239

2023-03-28 15:40 UTC, vjwilson requested changes
Agree with Nakul--let's update the test instead.

2023-03-28 16:31 UTC, theencee approved these changes

2023-03-28 16:36 UTC, theencee commented
@keyallis you should rebase. The style was fixed last night: https://github.com/stackrox/stackrox/pull/5413/files

2023-03-28 16:55 UTC, vjwilson approved these changes
FE change is OK

2023-03-28 17:56 UTC, merged