ROX-12394: remove scorecard namespace flag
stackrox/stackrox pull request #5442
Opened 2023-03-29 08:26 UTC by porridge

## Description

This was a temporary workaround for a problem that appeared after migration to prow. See ticket.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Revert the temporary commits
- [x] ~Unit test and regression tests added~
- [x] ~Evaluated and added CHANGELOG entry if required~
- [x] ~Determined and documented upgrade steps~
- [x] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

CI is sufficient.

2023-03-29 14:12 UTC, SimonBaeumer requested changes

2023-03-29 14:12 UTC, SimonBaeumer commented on operator/Makefile
> +	@tail -n 999999 $$KUBECONFIG || true
Why `-n 999999`? This looks like random number.

2023-03-29 14:12 UTC, SimonBaeumer commented on operator/tools/go.mod
> +replace github.com/operator-framework/operator-sdk v1.24.1 => github.com/porridge/operator-sdk v1.5.1-0.20230329122232-413d752ff864
Why is a fork necessary? I've looked into the change and to me at a first glance looked unrelated.

2023-03-29 14:23 UTC, porridge commented
This change is not ready for review, but there is no way to suppress the team-draco review request that gets added manually.
Maybe one could use the draft feature, but (a) I don't know whether that would help and (b) that in turn prevents tests from running.
I considered adding a [WiP] to PR title but I was afraid that the bot will try to be smart and this would have the same effect on tests as the draft status.
I added the `[do-not-merge]` label as last resort but I admit it's a little hidden there on the side...

(╯°□°)╯︵ ┻━┻ 

Suggestions most welcome on how to avoid such confusion in the process.

2023-04-24 10:57 UTC, porridge commented
Closing this for now, since https://github.com/kubernetes/client-go/issues/1241 might take a while to be processed.

2023-04-24 10:57 UTC, closed without merging