Multi-arch enablement changes for X/P/Z
stackrox/stackrox pull request #5502
Opened 2023-03-31 19:10 UTC by pratham-m

This PR intends to add multi-arch support for the groovy tests.
Test images used in respective test are changed to use alternate multi-arch images which support 3 platforms viz. `x86_64`, `ppc64le` and `s390x`.

Changes are verified manually using `./gradlew test --tests=TestName`

2023-04-03 08:08 UTC, gavin-stackrox approved these changes
LGTM once CI all-tests pass. Thanks.

2023-04-03 11:46 UTC, gavin-stackrox approved these changes
LGTM. VulnScanWithGraphQLTest failures do not appear to be related to this change.

2023-04-04 09:06 UTC, pratham-m commented
/test ocp-4-10-qa-e2e-tests
/test ocp-4-12-qa-e2e-tests

2023-05-09 20:25 UTC, pratham-m commented
/test ocp-4-10-qa-e2e-tests
/test ocp-4-12-qa-e2e-tests

2023-05-10 19:48 UTC, pratham-m commented
/retest-required
/test ocp-4-10-qa-e2e-tests
/test ocp-4-12-qa-e2e-tests

2023-05-15 17:59 UTC, gavin-stackrox commented
@pratham-m can you rebase this PR? It is no longer in sync with the openshift/release config AFAICT

2023-05-15 19:39 UTC, pratham-m commented
> @pratham-m can you rebase this PR? It is no longer in sync with the openshift/release config AFAICT

rebased to latest master

2023-05-15 19:39 UTC, pratham-m commented
/test ocp-4-10-qa-e2e-tests
/test ocp-4-12-qa-e2e-tests

2023-05-16 18:02 UTC, gavin-stackrox requested changes
I initially thought they were flakes but the persistent failures of `VulnScanWithGraphQLTest` are concerning. Unfortunately some change in the earlier tests are affecting this one.

2023-05-17 09:43 UTC, pratham-m commented
/test ocp-4-10-qa-e2e-tests
/test ocp-4-12-qa-e2e-tests

2023-05-22 15:12 UTC, pratham-m commented
We 

> I initially thought they were flakes but the persistent failures of `VulnScanWithGraphQLTest` are concerning. Unfortunately some change in the earlier tests are affecting this one.

ACK on the errors. we will have to debug these on a GKE setup.

2023-06-02 10:43 UTC, pratham-m commented
Closing this in favor for #6290 and #6292

2023-06-02 10:43 UTC, closed without merging