ROX-14917: Switch Helm charts versioning to respect Main major version
stackrox/stackrox pull request #5692
Opened 2023-04-14 13:32 UTC by msugakov

## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

2023-04-14 19:37 UTC, msugakov commented
I've done some manual testing. Will do a bit more and update the PR description whit what I've done.

2023-04-14 19:50 UTC, msugakov commented
/test ?

2023-04-14 19:51 UTC, msugakov commented
/test gke-postgres-upgrade-tests gke-upgrade-tests

2023-04-17 09:15 UTC, lvalerom approved these changes
LGTM

2023-04-17 10:11 UTC, Maddosaurus approved these changes
It is unfortunate that the reason why we didn't include major version in the Helm charts got lost in time. With that given, the new versioning scheme and changes make sense and LGTM!

2023-04-17 12:48 UTC, SimonBaeumer requested changes
I am worried about this change because it introduces an unexpected version number which creates an overhead in mapping the Helm version to the real StackRox version.

1) Is it possible to rename all previously released versions for Helm from `74.x.x` to `3.74.x`? I think it might be possible to have this as a one time change, the downside is customers must manually upgrade the Helm chart.

2) Is it possible to create a custom upgrade path in Helm similar by defining a previous version? Similar to how OLM manages its upgrade path. 
I could not find something, asked the questions in a [thread](https://kubernetes.slack.com/archives/C0NH30761/p1681729359162609) in #helm-users Kubernetes slack.

2023-04-17 13:28 UTC, SimonBaeumer approved these changes
Misha and I discussed offline. Mished showed me that there are two distinct versions in Helm, one is related to the Chart, and the other is the `appVersion`. The appVersion will reflect the product's version 1:1, giving Helm users a documented path to see the mapping between Helm and Application version.
🚢

2023-04-17 15:00 UTC, merged