Helm/Support - affinities and tolerations
stackrox/stackrox pull request #6470
Opened 2023-06-12 22:19 UTC by luciamota

## Description

This merge requests adds support for changing affinities 
Current values were defined as default values for all components.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Central services:

```
$ cd pkg/helm/charts/tests/centralservices
$ go test
PASS
ok      github.com/stackrox/rox/pkg/helm/charts/tests/centralservices   29.403s
```

Secured cluster:

```
$ cd pkg/helm/charts/tests/securedclusterservices
$ go test -v
PASS
ok      github.com/stackrox/rox/pkg/helm/charts/tests/securedclusterservices    5.837s
```

2023-06-14 07:34 UTC, SimonBaeumer requested changes
Hey @luciamota,
thank you for your contribution, the changes look very good!

We can merge this change after adding a unit tests for the Helm chart which test the affinity settings are applied to the resources.
The Helm chart unit tests are located here:
https://github.com/stackrox/stackrox/tree/24849214d64d3875230a13580804d1d60a794a97/pkg/helm/charts/tests

You can orient around the other Helm tests and find documentation about the helm-test tool [here](https://github.com/stackrox/helmtest).

It can be a bit tricky to work with them sometimes, if you need help please don't hesitate to ask.
If you have any feedback for docs on adding helm parameters I am happy to take it. Contributions like yours are important and should be as easy as possible.

//EDIT: I see now you've executed the tests during development.

2023-06-19 08:35 UTC, luciamota commented
Hello @SimonBaeumer, added some tests for default values and overridden. 😄

2023-06-20 07:29 UTC, SimonBaeumer approved these changes

2023-06-22 07:42 UTC, SimonBaeumer commented
Merged, the failing CI jobs are known flakes.

2023-06-22 07:43 UTC, SimonBaeumer commented
@luciamota We had a CI issue, the errors you are seeing. Can you rebase your PR once more on `master` to re-run the CI jobs?

2023-06-22 12:46 UTC, merged