ROX-17713: Disable telemetry in our ci runs
stackrox/stackrox pull request #6501
Opened 2023-06-14 08:57 UTC by 0x656b694d

## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

2023-06-14 08:57 UTC, 0x656b694d commented
Current dependencies on/for this PR:
* master
  * **PR #6420** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6420" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #6453** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6453" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #6501** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6501" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/6501?utm_source=stack-comment).

2023-06-15 16:49 UTC, gavin-stackrox requested changes
Does anything need to happen for operator installs?
https://github.com/stackrox/stackrox/blob/d639063506b89a3657db68346463dd575d3a2128/tests/e2e/lib.sh#L190

2023-06-15 16:49 UTC, gavin-stackrox commented on deploy/common/k8sbased.sh
> +        roxctl central generate --enable-telemetry=false "${ORCH}" "${EXTRA_ARGS[@]}" --output-dir="central-bundle" "${STORAGE}" "${STORAGE_ARGS[@]}"
Use the `add_args` func as elsewhere

2023-06-16 17:37 UTC, gavin-stackrox approved these changes
LGTM though how to know if it is working as intended without running CI?

2023-06-29 10:27 UTC, janisz approved these changes

2023-07-04 07:56 UTC, merged