ROX-17683: Enable telemetry by default for release operator versions
stackrox/stackrox pull request #6542
Opened 2023-06-15 16:17 UTC by 0x656b694d

## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

2023-06-15 16:17 UTC, 0x656b694d commented
Current dependencies on/for this PR:
* master
  * **PR #6420** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6420" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #6453** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6453" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #6501** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6501" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #6542** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6542" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/6542?utm_source=stack-comment).

2023-06-16 09:02 UTC, kovayur requested changes
Overall good, need to generate the files correctly and address a few nitpicks.

2023-06-16 12:58 UTC, 0x656b694d commented on operator/bundle/manifests/platform.stackrox.io_centrals.yaml
> +                        default: true
Right, done.

2023-06-16 13:36 UTC, 0x656b694d commented on operator/pkg/central/values/translation/translation.go
> +		telemetry.Enabled = &[]bool{false}[0]
The logic moved to `getTelemetryValues()`.

2023-06-16 14:07 UTC, kovayur approved these changes
LGTM

2023-06-27 12:12 UTC, janisz approved these changes

2023-07-04 07:55 UTC, merged