refactor: Make '/v1/database/status' authenticated.
stackrox/stackrox pull request #6700
Opened 2023-06-27 15:20 UTC by rukletsov

## Description

Originally, `/v1/database/status` was open to the world to allow consumers—primarily ACS UI—to to zero in on the problem with the database before authentication because rendering login screen requires fetching info on auth providers from the database. However, ACS UI does not call this endpoint from the login screen and apparently does not plan to do so in the nearest future.

Given the primary use case is off the table, this PR tightens access for the endpoint to only authenticated users.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] ~Unit test and regression tests added~
- [ ] ~Evaluated and added CHANGELOG entry if required~
- [ ] ~Determined and documented upgrade steps~
- [ ] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

Manual test TBD.

2023-06-27 16:05 UTC, vjwilson requested changes
I discovered a weird edge case, where if this status calls fails once you are logged in, we are still showing the "Backup your database before the upcoming Postgres migration..." banner, too.

Would you like me to push a change to this branch ?

2023-06-27 16:37 UTC, rukletsov commented
> I discovered a weird edge case, where if this status calls fails once you are logged in, we are still showing the "Backup your database before the upcoming Postgres migration..." banner, too.
> 
> Would you like me to push a change to this branch ?

Oh yes, if you prefer, please.

2023-06-27 19:58 UTC, vjwilson commented
> I discovered a weird edge case, where if this status calls fails once you are logged in, we are still showing the "Backup your database before the upcoming Postgres migration..." banner, too.
> 
> Would you like me to push a change to this branch ?

Ooops, turns out it was user-dismissible, and different ports matter (8000).

We probably should pull that warning out, but in a separate PR.

Approved.

2023-06-27 19:58 UTC, vjwilson approved these changes

2023-06-28 09:54 UTC, dashrews78 approved these changes
you need to run make on protos for the comment change.  Otherwise, LGTM

2023-06-30 08:12 UTC, merged