ROX-18838: discard unused Docker socket mount in Collector container
stackrox/stackrox pull request #7247
Opened 2023-08-03 09:09 UTC by ovalenti

## Description

The current definition of the Collector _daemonset_ contains a volume to access to the Docker socket. This is not used anymore and could cause security concern.

Let's discard it.

## Checklist
- [ ] Investigated and inspected CI test results

2023-08-03 09:59 UTC, ovalenti commented
/test all

2023-08-04 17:49 UTC, connorgorman requested changes
Unfortunately, this would break Docker CIS compliance benchmark which we have not officially deprecated and will be marked for deprecation in 4.2 and deprecated in 4.3 (afaik). This PR will need to be significantly more complex in order to give a toggle in the operator / helm to be able to exclude the docker sock if we want to do something for 4.2

2023-08-07 08:53 UTC, ovalenti commented
> Unfortunately, this would break Docker CIS compliance benchmark which we have not officially deprecated and will be marked for deprecation in 4.2 and deprecated in 4.3 (afaik). This PR will need to be significantly more complex in order to give a toggle in the operator / helm to be able to exclude the docker sock if we want to do something for 4.2

@connorgorman, I think that the proposed change affects only the `collector` container and that `compliance` will still have `/host/var/lib/docker` via [`host-root-ro`](https://github.com/stackrox/stackrox/blob/master/image/templates/helm/stackrox-secured-cluster/templates/collector.yaml#L206)

But I am not sure I get the whole picture about CIS Docker CIS compliance.

2023-08-07 17:12 UTC, connorgorman approved these changes
Makes sense for collector

2023-08-08 08:36 UTC, ovalenti commented
/retest

2023-08-08 15:58 UTC, ovalenti commented
/retest

2023-08-10 05:52 UTC, ovalenti commented
/retest

2023-08-14 13:12 UTC, merged