Add skip-tls-verify flag for opm render
stackrox/stackrox pull request #7279
Opened 2023-08-04 14:50 UTC by kovayur

## Description

Add `skip-tls-verify` flag for opm render to be able to build index image with insecure registry

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed
Tested locally

2023-08-07 05:21 UTC, porridge requested changes
I think this PR will need some rationale on why we think we can still build securely without using TLS? :thinking:

2023-08-07 05:21 UTC, porridge commented on operator/hack/build-index-image.sh
> +  --skip-tls-verify    Skip TLS certificate verification for container image registries while pulling bundles
```suggestion
  --skip-tls-verify    Skip TLS certificate verification for container image registries while pulling bundles.
```

2023-08-07 08:02 UTC, kovayur commented
@porridge I updated the description and added a rationale.

2023-08-07 09:37 UTC, porridge approved these changes

2023-08-08 08:36 UTC, kovayur commented
gke-qa-e2e-tests failed because of the flake (ROX-16290), merging

2023-08-08 08:36 UTC, merged