ROX-17702: `GetByQuery`, paginated by time chunks
stackrox/stackrox pull request #7472
Opened 2023-08-16 16:21 UTC by 0x656b694d

## Description

Make use of the newly implemented query by timerange.

## Checklist
- [x] Investigated and inspected CI test results
- [x] Unit test and regression tests added
- [ ] ~Evaluated and added CHANGELOG entry if required~
- [ ] ~Determined and documented upgrade steps~
- [ ] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

Unit tests.
TODO: local e2e.

2023-08-17 17:38 UTC, connorgorman commented on central/productusage/datastore/securedunits/datastore_impl.go
> +	for offset := 0; ; offset += page {
This does one extra query than necessary. We should check that len(units) < page which means that we are on the last page. Only if the exact number of elements matches page then we'll do the extra query which should be rare

2023-08-17 17:39 UTC, connorgorman commented on central/productusage/datastore/securedunits/datastore_impl.go
> +		from = time.Unix(0, 0)
why is this necessary?

2023-08-17 17:40 UTC, connorgorman commented on central/productusage/datastore/securedunits/datastore_impl.go
> +	pagination := search.NewPagination().
The sort needs to be descending right? Default sort order is asc which is lowest value first

2023-08-17 17:41 UTC, connorgorman commented on central/productusage/datastore/securedunits/datastore_impl_test.go
> +func (suite *UsageDataStoreTestSuite) TestGetMax() {
I would consider writing an integration test that uses a real postgres DB to ensure that the queries are working correctly

2023-08-17 17:44 UTC, connorgorman requested changes
Some comments about the implementation of finding the max that probably need to be corrected

2023-08-21 13:24 UTC, 0x656b694d commented
Current dependencies on/for this PR:

* master
  * **PR #7403**
    * **PR #7136**
      * **PR #7137**
        * **PR #7138**
          * **PR #7179**
            * **PR #7472** 👈
          * **PR #7160**
          * **PR #7053**

2023-08-21 18:16 UTC, connorgorman approved these changes
Small comments on the error reporting, but lg, thanks for all the changes

2023-08-23 15:07 UTC, merged