feat(hackathon) multiple role selection in UI at API token generation
stackrox/stackrox pull request #7901
Opened 2023-09-27 09:03 UTC by rhybrillou

## Description

See title

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

On a local deployment, go to `Platform Configuration > Integrations`, then choose `API Tokens`.
Click `Generate token`, give the token a name (here 'Test'), select `Sensor creation` and `Network graph viewer`, and click `Generate`.
![Screenshot 2023-09-26 at 15 11 46](https://github.com/stackrox/stackrox/assets/91869377/91e51db8-1860-4034-b6b8-6b78cb2463d7)

Then go to the API token list and display the newly created token. It should contain the two selected roles.
![Screenshot 2023-09-27 at 11 02 45](https://github.com/stackrox/stackrox/assets/91869377/fb2dca6d-6e88-46bd-bcc5-af2fe6629cfe)

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2024-01-25 14:49 UTC, janisz requested changes

2025-11-18 09:33 UTC, rhybrillou commented
/retest

2026-04-06 15:33 UTC, sachaudh commented
Noticed this PR has been open since 2023. Some changes were added 5 months ago. @rhybrillou, is this PR still being worked on? The UI team was assigned, and we're trying to clean up any open PRs that need to be reviewed.

2026-05-12 13:50 UTC, rhybrillou commented
> Noticed this PR has been open since 2023. Some changes were added 5 months ago. @rhybrillou, is this PR still being worked on? The UI team was assigned, and we're trying to clean up any open PRs that need to be reviewed.

This PR is part of an old hackathon project and did not land. I'll close it for now, and re-open if/when the need resurfaces.

2026-05-12 13:50 UTC, closed without merging