ROX-19955: Prometheus resources in sensor upgrader
stackrox/stackrox pull request #7946
Opened 2023-10-02 14:34 UTC by stehessel

## Description

The sensor upgrader is used when sensor is installed via manifest download, while at a later point central is updated to a newer version. The upgrader will then attempt to upgrade sensor to the same upgraded version. As part of the upgrade process, it currently checks that all resources are created in the stackrox namespace. With `4.2.0`, when integration with OpenShift monitoring is enabled, sensor additionally creates Prometheus resources in system namespaces.

This leads to a failure during the upgrader pre-flight check when upgrading from `4.1.x` to `4.2.0` for OpenShift secured clusters. As a fix for this issue, this PR adds the Prometheus resources to an exception list.

## Testing Performed

To reproduce the original issue:
* Install central via Helm chart version `4.1.3`.
* Install sensor via manifest download by running `./sensor.sh`.
* Upgrade central to `4.2.0` via `helm upgrade`.
* In the cluster overview page, the sensor upgrader shows an error in the pre-flight check.

To test the fix:
* Install central via Helm chart version `4.1.3`.
* Install sensor via manifest download by running `./sensor.sh`.
* Upgrade central to `4.2.0-fix` via `helm upgrade`.
* In the cluster overview page, the sensor upgrader successfully performs the upgrade.

2023-10-04 18:55 UTC, dhaus67 requested changes
We should have a unit test covering the exception conditions.

Also, is there someone else that definitely _needs_ to take a look at that, like Maple / Draco?

2023-10-04 18:55 UTC, dhaus67 commented on sensor/upgrader/preflight/namespace.go
> +func isException(resource *k8sobjects.ObjectRef) bool {
```suggestion
func matchesException(resource *k8sobjects.ObjectRef) bool {
```

2023-10-04 18:55 UTC, dhaus67 commented on sensor/upgrader/preflight/namespace.go
> +		doCheck := !isException(&act.ObjectRef)
```suggestion
		noException := !isException(&act.ObjectRef)
```

2023-10-05 08:08 UTC, fredrb reviewed
The current change seems ok. But I wonder why are we implementing a fine-grained exception list rather than changing the premise that things can only be installed in `common.Namespace`? 

I don't have the historical context because this was here long before I joined, but my understanding is that we want to make sure that things weren't installed in the incorrect namepsace. I.e.: if the upgrader had incorrectly determined resources to be installed elsewhere, but stackrox should be confined to `stackrox` namespace. 

Should't we change this premise, and say that ACS can be installed across a set of namespaces, like `stackrox`, `kube-system` and `openshift-monitoring`, without a distinction for which resource type is allowed in each? 

The reasoning for this is to avoid exactly the bug this PR is fixing in the future -- where we need a new resource to be installed, and need to patch sensor to support that.

2023-10-05 08:10 UTC, fredrb commented
By the way, disregard `ci/prow/ocp-4-10-sensor-profiling`.

2023-10-05 08:29 UTC, stehessel commented
> The current change seems ok. But I wonder why are we implementing a fine-grained exception list rather than changing the premise that things can only be installed in common.Namespace?

Are you suggesting to simply drop the namespace pre-flight check? I would agree that it doesn't server much purpose, because the resources are defined by the Helm chart anyway, which the upgrader simply renders. The upgrader doesn't even decide the resource definitions / namespaces, but is testing for them.

The reason I didn't drop the check is that I wanted the most minimal fix, but indeed maybe it's better to drop completely.

2023-10-05 17:08 UTC, stehessel commented
Decided to keep the namespace check for the scope of this fix to reduce the chance of further regression. It's not 100% clear that we can simply drop the namespace check altogether, although I do believe that it is likely the case. However, that would require some more thorough investigation, which I don't think should block the fix.

@fredrb If you like I can create a ticket to properly remove the namespace check and file it under Sensor tech debt.

2023-10-05 17:12 UTC, dhaus67 approved these changes

2023-10-05 18:51 UTC, stehessel commented
/retest

2023-10-05 23:32 UTC, stehessel commented
@dhaus67 Sorry to re-ping, but could you take another look? I actually found another location in which the upgrader explicitly assumes that resources live in certain namespaces. I extended this list to the OpenShift monitoring case and commented on how to extend this to other resources in the future - if it ever comes to that.

2023-10-06 03:13 UTC, stehessel commented
/retest

2023-10-06 07:54 UTC, fredrb approved these changes

2023-10-06 09:11 UTC, dhaus67 approved these changes

2023-10-06 14:27 UTC, merged