ROX-20175: Update all vulnerability requests to use image scope
stackrox/stackrox pull request #8158
Opened 2023-10-13 16:17 UTC by md2119

## Description

All vulnerability exception requests will be represented using `.scope.imageScope` fields starting 4.4. It simplifies the vulnerability request scope representation dramatically. The global scope exceptions will have `.scope.imageScope` as below:
```
{
  registry: ".*",
  remote: ".*",
  tag: ".*",
}
```
The global scope support for `Risk assessment workflow` (2nd generation exception management) was never announced. However, since the fields are available at APIs, we must ensure that we migrate any globally scoped vulnerability requests.
A notice for deprecation of `.scope.globalScope` is not required because `/v1/cve/requests` are deprecated and notified and `v2` APIs do not expose `storage.VulnerabilityRequest`.

**Note that this PR will not be merged until the 4.3 release is cut.**

## Checklist
- [ ] Investigated and inspected CI test results
- [X] Unit test and regression tests added
- ~Evaluated and added CHANGELOG entry if required~
- ~Determined and documented upgrade steps~
- ~Documented user-facing changes~

If any of these don't apply, please comment below.

## Testing Performed
Unit Test

2023-10-16 10:08 UTC, dashrews78 commented
First pass through, looks good.  I know of at least 2 other migrations in flight, so I will hold off approval until those migrations land and we have rebased off them.

2023-10-27 15:57 UTC, dashrews78 commented on migrator/migrations/m_194_to_m_195_vuln_request_global_scope/migration.go
> +	startSeqNum = 195
```suggestion
	startSeqNum = 194
```

2023-10-27 16:02 UTC, dashrews78 requested changes
startSeqNum in `migration.go`.
Other than that it looks good, but that one is important.

2023-10-27 19:32 UTC, md2119 commented
Did a manual upgrade from 4.2.0 to this PR build

2023-10-27 19:45 UTC, dashrews78 commented
FTR, I think https://github.com/stackrox/stackrox/pull/8346 busted the upgrade test.

2023-10-27 20:33 UTC, md2119 commented
> FTR, I think #8346 busted the upgrade test.


The eclipse continues

2023-10-30 11:08 UTC, dashrews78 approved these changes

2023-10-30 17:15 UTC, merged