ROX-20291: Sensor reconciler component
stackrox/stackrox pull request #8282
Opened 2023-10-20 10:18 UTC by fredrb

## Description

This component is responsible for making sure that the deduper state is passed to `hash_reconciler` and that sensor messages are produced and emitted to central. 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] ~~Evaluated and added CHANGELOG entry if required~~
- [ ] ~~Determined and documented upgrade steps~~
- [ ] ~~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

- [ ] CI
- [ ] Manual tests 

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2023-10-20 10:52 UTC, lvalerom requested changes
LGTM blocking only because I think you forgot to `defer` one of the locks.

2023-10-20 10:52 UTC, lvalerom commented on sensor/common/reconciliation/component.go
> +	c.stateLock.Unlock()
```suggestion
	defer c.stateLock.Unlock()
```

2023-10-20 11:08 UTC, fredrb commented on sensor/common/reconciliation/component.go
> +	c.stateLock.Unlock()
Whoops

2023-10-23 07:17 UTC, lvalerom approved these changes
LGTM

2023-10-23 16:07 UTC, merged