ROX-17653: add pods names to pod restart junit
stackrox/stackrox pull request #8378
Opened 2023-10-26 16:35 UTC by janisz

## Description

Add pod names in junit restarted pod report.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

Manually run script on payload I found in Jira. It correctly reports pod names

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2023-10-26 19:02 UTC, gavin-stackrox requested changes
I have a suggestion (which is feature creep so feel free to ignore) but in case you are up for it: Add a link to the logfile artifact similar to how this is done in https://github.com/stackrox/stackrox/blob/2404eb695ff6542d8c9525e695d03040effd8d06/qa-tests-backend/scripts/lib.sh#L90

2023-10-27 17:03 UTC, janisz commented on tests/e2e/lib.sh
> +            pods=$(echo $check_out | grep "copied to Artifacts" | cut -d- -f1,3 | sort -u | tr '\n' ' ')
ok, added a comment but keep the old log message as I've already have a parse script that is working.

2023-10-27 17:04 UTC, janisz commented
> I have a suggestion (which is feature creep so feel free to ignore) but in case you are up for it: Add a link to the logfile artifact similar to how this is done in

Let's skip it. Having a pod name and a link to CI should be enough to quickly locate the file.

2023-10-27 17:25 UTC, gavin-stackrox approved these changes

2023-10-27 17:25 UTC, gavin-stackrox commented on scripts/ci/logcheck/check-restart-logs.sh
> +                echo "$(basename "${logfile}") copied to Artifacts" # do not change - required by pod restart check
nit:
```suggestion
                # do not change - required by pod restart check (check_for_stackrox_restarts())
                echo "$(basename "${logfile}") copied to Artifacts"
```

2023-10-31 15:56 UTC, janisz commented on tests/e2e/lib.sh
> +            save_junit_failure "Pod Restarts" "${file}" "${check_out}"
```suggestion
            save_junit_failure "Pod Restarts" "${pods}" "${check_out}"
```

2023-10-31 17:34 UTC, merged