refactor(CI): have a single source of GKE defaults
stackrox/stackrox pull request #8396
Opened 2023-10-27 17:20 UTC by gavin-stackrox

## Description

Per title. The existing logic has 3 locations for defaults and is confusing.

## Checklist
- [ ] Investigated and inspected CI test results

## Testing Performed

Ensure tests with parameter overrides get the correct values:
- [ ] gke-scale
- [ ] gke-upgrade

2023-10-27 17:22 UTC, gavin-stackrox commented
/test gke-scale-tests gke-upgrade-tests

2023-10-30 07:43 UTC, porridge requested changes

2023-10-30 07:43 UTC, porridge commented on .openshift-ci/clusters.py
> +        if self.num_nodes is not None:
Reportedly it's more pythonic to just do `if self.num_nodes:`.
Similarly below.

2023-10-30 07:43 UTC, porridge commented on scripts/ci/gke.sh
>      if [[ "$#" -lt 1 ]]; then
Might be good to fail early rather than silently ignore args.
```suggestion
    if [[ "$#" -ne 1 ]]; then
```

2023-10-30 07:43 UTC, porridge commented on .openshift-ci/clusters.py
> +                self.cluster_id,            ]
```suggestion
                self.cluster_id,
            ]
```
Alternatively, put them all on a single line now that there are just 3. Replacing `GKECluster.` with `self.` will help with line length if needed.

2023-10-31 19:10 UTC, connorgorman approved these changes

2023-11-01 07:15 UTC, porridge approved these changes

2023-11-01 07:15 UTC, merged