Added copunt endpoint for scan configuration settings
stackrox/stackrox pull request #8467
Opened 2023-11-02 00:45 UTC by ksurabhi91

This PR adds count end points for compliance operator scan configurations, profiles and scan results 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

TODO(replace-me)  
Use this space to explain **how you validated** that **your change functions exactly how you expect it**.
Feel free to attach JSON snippets, curl commands, screenshots, etc. Apply a simple benchmark: would the information you
provided convince any reviewer or any external reader that you did enough to validate your change.

It is acceptable to assume trust and keep this section light, e.g. as a bullet-point list.

It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change only.  
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case you are
responsible for the change after it gets merged which includes reverting, fixing, etc. Make sure you validate the change
ASAP after it gets merged or explain in PR when the validation will be performed.  
Explain here why you skipped testing in case you did so.

Have you created automated tests for your change? Explain here which validation activities you did manually and why so.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2023-11-02 13:57 UTC, dashrews78 commented on proto/api/v2/compliance_scan_configuration_service.proto
> +          get:"/v2/compliance/scan/configurations/count"
```suggestion
          get:"/v2/compliance/scan/count/configurations"
```
To avoid conflicts I think we need to flip the URL.

2023-11-02 14:04 UTC, dashrews78 commented on central/complianceoperator/v2/scanconfigurations/service/service_impl.go
> +	scanConfigs, err := s.complianceScanSettingsDS.GetScanConfigurations(ctx, parsedQuery)
I think a better solution would be to:

- add the indexer to the datastore
- create a count in the datastore
- have the datastore count call the indexer
- have this service call the datastore count method.

The `store/index.go` already exists and has a `Count` that takes in a query.  We just need to wire up the datastore to use it.

2023-11-06 19:09 UTC, theencee commented
Can you rebase against master?

2023-11-09 19:56 UTC, dashrews78 commented on proto/api/v2/compliance_scan_configuration_service.proto
> +          get:"/v2/compliance/scan/count/configurations"
```suggestion
          get: "/v2/compliance/scan/count/configurations"
```

2023-11-09 19:56 UTC, dashrews78 commented on proto/api/v2/compliance_scan_configuration_service.proto
> +    int32                                       count                =1;
```suggestion
    int32  count = 1;
```

2023-11-09 19:56 UTC, dashrews78 commented on proto/api/v2/compliance_results_service.proto
> +    int32     count=1;
```suggestion
    int32 count = 1;
```

2023-11-09 19:59 UTC, dashrews78 commented on central/complianceoperator/v2/checkresults/datastore/datastore.go
> +	CountCheckResults(ctx context.Context, q *v1.Query) (int, error)
Add a comment

2023-11-09 20:02 UTC, dashrews78 commented on central/complianceoperator/v2/checkresults/datastore/index/index.go
> +package index
I'm not sure this file is necessary since the `searcher` interface defines a `Count`

2023-11-09 20:19 UTC, dashrews78 commented on central/complianceoperator/v2/checkresults/service/service_impl.go
> +	count, err := s.complianceResultsDS.CountCheckResults(ctx, parsedQuery)
nit:  new line before this.

2023-11-09 20:19 UTC, dashrews78 commented on central/complianceoperator/v2/checkresults/service/service_impl.go
> +	return res, nil
```suggestion
	return &v2.CountComplianceScanResults{
		Count: int32(count),
	}, nil
```

2023-11-09 20:22 UTC, dashrews78 commented on central/complianceoperator/v2/scanconfigurations/datastore/index/index.go
> +package index
Same question on whether this is actually needed.

2023-11-09 20:23 UTC, dashrews78 commented on proto/api/v2/compliance_scan_configuration_service.proto
> +message ComplianceScanConfigurationCount{
```suggestion
message ComplianceScanConfigurationsCount{
```

2023-11-09 20:23 UTC, dashrews78 commented on central/complianceoperator/v2/scanconfigurations/service/service_impl.go
> +func (s *serviceImpl) GetComplianceScanConfigurationCount(ctx context.Context, request *v2.RawQuery) (*v2.ComplianceScanConfigurationCount, error) {
```suggestion
func (s *serviceImpl) GetComplianceScanConfigurationsCount(ctx context.Context, request *v2.RawQuery) (*v2.ComplianceScanConfigurationCount, error) {
```

2023-11-09 20:24 UTC, dashrews78 commented on central/complianceoperator/v2/scanconfigurations/service/service_impl.go
> +	}
nit:  new line after this

2023-11-09 20:24 UTC, dashrews78 commented on central/complianceoperator/v2/scanconfigurations/service/service_impl.go
> +	return res, nil
same suggestion as the other service.

2023-11-09 20:30 UTC, dashrews78 requested changes
I think you should add test cases to the results `service_impl`.  And probably either a datastore or searcher test.  I think I'd prefer the datastore.

2023-11-13 23:40 UTC, ksurabhi91 commented on central/complianceoperator/v2/scanconfigurations/datastore/search/search_impl.go
> +	return ds.searcher.Count(ctx, q)
Do we need to check for permission in search impl since permission is already checked in data store impl before calling searcher.count

2023-11-13 23:45 UTC, theencee commented on central/complianceoperator/v2/scanconfigurations/datastore/search/search_impl.go
> +	return ds.searcher.Count(ctx, q)
Yes. It's not that expensive and it's safer that way (in case it gets used elsewhere)

2023-11-14 20:41 UTC, ksurabhi91 commented
/retest

2023-11-17 01:19 UTC, theencee approved these changes

2023-11-17 01:19 UTC, theencee commented on central/complianceoperator/v2/scanconfigurations/datastore/search/search_impl.go
> +	complianceOperatorSAC = sac.ForResource(resources.ComplianceOperator)
[nit]
```suggestion
	scanConfigurationsSAC = sac.ForResource(resources.ComplianceOperator)
```

2023-11-22 17:48 UTC, ksurabhi91 commented
/rerun

2023-11-27 11:07 UTC, dashrews78 approved these changes
looks like there is one nit left about a newline.  I trust you to resolve that as you see fit.

2023-11-29 01:56 UTC, merged