fix: don't block secret informer cache sync
stackrox/stackrox pull request #9845
Opened 2024-02-09 12:41 UTC by stehessel

## Description

Add a timeout condition to the informer cache sync. This is useful because we don't want to block the main loop forever. In particular, this came up in a recent upgrade test failure. The upgrade test switches out the Central image instead of performing a proper Helm upgrade - as a result, k8s roles were not set correctly. This caused the informer to never connect due to a unauthorized access. The test should be adapted to perform a proper Helm upgrade. Nevertheless, such issues should not cause Central to block.

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

### Here I tell how I validated my change

gke-upgrade test is now passing.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

2024-02-09 23:31 UTC, stehessel commented
/test all

2024-02-09 23:34 UTC, stehessel commented
/test gke-upgrade-tests

2024-02-10 00:17 UTC, stehessel commented
/test all

2024-02-10 00:17 UTC, stehessel commented
/test gke-upgrade-tests

2024-02-10 13:59 UTC, stehessel commented
/retest

2024-02-12 12:41 UTC, janisz reviewed
Could you split it into 2 PRs
1. renames
2. actual change
Currently the most changes is due to rename

2024-02-12 15:13 UTC, stehessel commented
Current dependencies on/for this PR:
* `master`
  * **PR #9845** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/9845?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #9878** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/9878?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/9845?utm_source=stack-comment).

2024-02-12 15:15 UTC, stehessel commented
> Could you split it into 2 PRs

done

2024-02-12 15:28 UTC, stehessel commented
/test gke-upgrade-tests

2024-02-12 15:29 UTC, stehessel commented
/retest

2024-02-13 15:08 UTC, janisz requested changes

2024-02-13 15:08 UTC, janisz commented on pkg/secretinformer/informer.go
> +	synced := sif.WaitForCacheSync(stopWait.Done())
What if we break due to a timeout?

2024-02-14 01:12 UTC, stehessel commented
/test gke-upgrade-tests

2024-02-14 01:13 UTC, stehessel commented
> Handle returned error and store information that the informer is not running and it could generate errors
Add log line in GetCredentials about possible issues
Use context with timeout instead of concurrency Any with timeout

I decided to remove the problematic `WaitForCacheSync` entirely and instead expose the informer handler to track the sync status in `GetCredentials`. Also switched to context as discussed.

2024-02-14 03:53 UTC, stehessel commented
/retest

2024-02-15 14:25 UTC, merged